Repository abhisheks008/DL-Simplified, pull requests merged in 2022-08, with the labels that each got.

#78 Heartbeat Classification using ECG
  Heartbeat Classification using ECG/Dataset/README.md
  Heartbeat Classification using ECG/Images/00.png
  Heartbeat Classification using ECG/Images/01.png
  Heartbeat Classification using ECG/Images/02.png
  Heartbeat Classification using ECG/Images/03.png
  Heartbeat Classification using ECG/Images/04.png
  Heartbeat Classification using ECG/Images/05.png
  Heartbeat Classification using ECG/Images/06.png
  Heartbeat Classification using ECG/Images/07.png
  Heartbeat Classification using ECG/Images/08.png
  Heartbeat Classification using ECG/Images/09.png
  Heartbeat Classification using ECG/Images/10.png
  Heartbeat Classification using ECG/Images/11.png
  Heartbeat Classification using ECG/Images/12.png
  Heartbeat Classification using ECG/Images/13.png
  Heartbeat Classification using ECG/Images/14.png
  Heartbeat Classification using ECG/Model/README.md
  Heartbeat Classification using ECG/Model/ecg-cnn-model01.ipynb
  Heartbeat Classification using ECG/requirements.txt.txt
Labels: Changes Requested

#81 Hot dog classification
  HotDog Classification/Dataset/README.md
  HotDog Classification/Images/img1.JPG
  HotDog Classification/Images/img10.JPG
  HotDog Classification/Images/img2.JPG
  HotDog Classification/Images/img3.JPG
  HotDog Classification/Images/img4.JPG
  HotDog Classification/Images/img5.JPG
  HotDog Classification/Images/img6.JPG
  HotDog Classification/Images/img7.JPG
  HotDog Classification/Images/img8.JPG
  HotDog Classification/Images/img9.JPG
  HotDog Classification/Model/.ipynb_checkpoints/hotdog-classification-model-checkpoint.ipynb
  HotDog Classification/Model/hotdog-classification-model.ipynb
  HotDog Classification/README.md
  HotDog Classification/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Advanced

#90 Fraudulent-Transactions-Detection
  Fraudulent Transactions Detection/Dataset/README.md
  Fraudulent Transactions Detection/Images/Dataset head.png
  Fraudulent Transactions Detection/Images/acc_com_lr_rfc.png
  Fraudulent Transactions Detection/Images/lr_cm.png
  Fraudulent Transactions Detection/Images/rfc_cm.png
  Fraudulent Transactions Detection/Model/README.md
  Fraudulent Transactions Detection/Model/fraud_transaction_detection.ipynb
  Fraudulent Transactions Detection/Model/kaggle.json
  Fraudulent Transactions Detection/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Advanced

#82 Handwriting Recognition Project
  Handwriting Recognition Project/.vscode/settings.json
  Handwriting Recognition Project/Dataset/README.md
  Handwriting Recognition Project/Images/Accuracy.jpg
  Handwriting Recognition Project/Images/DistbNames.jpg
  Handwriting Recognition Project/Images/Histogram.jpg
  Handwriting Recognition Project/Images/datasetImg.jpg
  Handwriting Recognition Project/Images/heatmap.jpg
  Handwriting Recognition Project/Model/Handwriting_Recognition.ipynb
  Handwriting Recognition Project/Model/README.md
  Handwriting Recognition Project/requirements.txt
Labels: Changes Requested

#97 Credit card fraud detection #66
  Credit Card Fraud Detection/Dataset/README.md
  Credit Card Fraud Detection/Images/Recall-Precision-Curve-ANN.png
  Credit Card Fraud Detection/Images/Recall-Precision-Curve-logistic-regression.png
  Credit Card Fraud Detection/Images/confusion-matrix-ANN.png
  Credit Card Fraud Detection/Images/confusion-matrix-logistic-regression.png
  Credit Card Fraud Detection/Images/dataset-cover.jpg
  Credit Card Fraud Detection/Images/dataset-head.jpg
  Credit Card Fraud Detection/Images/model-summary.jpg
  Credit Card Fraud Detection/Model/README.md
  Credit Card Fraud Detection/Model/credit_card.ipynb
  Credit Card Fraud Detection/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Intermediate

#98 Yahoo Answers NLP #35
  Yahoo Answers NLP/Dataset/README.md
  Yahoo Answers NLP/Images/CNN Plot.png
  Yahoo Answers NLP/Images/LSTM Plot.png
  Yahoo Answers NLP/Images/box plot.png
  Yahoo Answers NLP/Images/yahoo-answers.png
  Yahoo Answers NLP/Model/Yahoo_Answers_NLP.ipynb
  Yahoo Answers NLP/README.md
  Yahoo Answers NLP/requirements.txt
Labels: Changes Requested

#102 Shoe classification
  Shoes Classification/.gitignore
  Shoes Classification/Dataset/README.md
  Shoes Classification/Images/Accuracy.png
  Shoes Classification/Images/output.png
  Shoes Classification/Images/training_validation_loss.png
  Shoes Classification/Model/README.md
  Shoes Classification/Model/Shoe_Classification.ipynb
  Shoes Classification/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Intermediate

#93 Issue #79 Blood Disease Detection
  Blood Disease Detection/Datasets/README.md
  Blood Disease Detection/Images/adadelta_scc_relu_accuracy.svg
  Blood Disease Detection/Images/adadelta_scc_relu_loss.svg
  Blood Disease Detection/Images/adagrad_scc_relu_accuracy.svg
  Blood Disease Detection/Images/adagrad_scc_relu_loss.svg
  Blood Disease Detection/Images/adam_scc_relu_accuracy.svg
  Blood Disease Detection/Images/adam_scc_relu_loss.svg
  Blood Disease Detection/Images/all_combined_accuracy.svg
  Blood Disease Detection/Images/all_combined_loss.svg
  Blood Disease Detection/Images/cell_types.png
  Blood Disease Detection/Images/model_summary.png
  Blood Disease Detection/Images/rmsprop_scc_relu_accuracy.svg
  Blood Disease Detection/Images/rmsprop_scc_relu_loss.svg
  Blood Disease Detection/Images/sgd_scc_relu_accuracy.svg
  Blood Disease Detection/Images/sgd_scc_relu_loss.svg
  Blood Disease Detection/Model/BloodDisease.ipynb
  Blood Disease Detection/Model/README.md
  Blood Disease Detection/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Intermediate

#108 Keep Babies Safe #71
  HackerEarth Keep Babies Safe/Dataset/README.md
  HackerEarth Keep Babies Safe/Images/Cluster.png
  HackerEarth Keep Babies Safe/Images/Head.png
  HackerEarth Keep Babies Safe/Images/Sample.png
  HackerEarth Keep Babies Safe/Images/tesseract_result.png
  HackerEarth Keep Babies Safe/Model/README.md
  HackerEarth Keep Babies Safe/Model/keepbabiessafe-ssoc.ipynb
  HackerEarth Keep Babies Safe/Model/keepbabiessafe-ssoc_MAIN.ipynb
  HackerEarth Keep Babies Safe/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Advanced
