Repository abhisheks008/DL-Simplified, pull requests merged in 2022-09, with the labels that each got.

#121 Issue #52 : Lending Club Loan Analysis
  Lending Club Loan Analysis/Datasets/README.md
  Lending Club Loan Analysis/Images/Accuracy of Model.PNG
  Lending Club Loan Analysis/Images/Area Plots/Area Plot 2.PNG
  Lending Club Loan Analysis/Images/Area Plots/Area Plot 3.PNG
  Lending Club Loan Analysis/Images/Area Plots/Area Plot 4.PNG
  Lending Club Loan Analysis/Images/Area Plots/Area Plots .PNG
  Lending Club Loan Analysis/Images/Confusion Matrix.PNG
  Lending Club Loan Analysis/Images/Important Plots/Plot 1.PNG
  Lending Club Loan Analysis/Images/Important Plots/Plot 2.PNG
  Lending Club Loan Analysis/Images/Important Plots/Plot 3.PNG
  Lending Club Loan Analysis/Images/Important Plots/Plot 4.PNG
  Lending Club Loan Analysis/Images/Important Plots/Plot 5.PNG
  Lending Club Loan Analysis/Images/Important Plots/Plot 6.PNG
  Lending Club Loan Analysis/Models/Lending_Club_Loan_Analysis.ipynb
  Lending Club Loan Analysis/Models/Lending_Club_Loan_Analysis_(Logistic_Regression_,_Decision_Tree_,_Random_Forest,ANN)_Model.ipynb
  Lending Club Loan Analysis/Models/Lending_Club_Loan_Analysis_KNN_Model.ipynb
  Lending Club Loan Analysis/Models/README.md
  Lending Club Loan Analysis/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Intermediate

#118 Driving Behavior Identification #65
  DATASET.md
  DRIVING BEHAVIOUR IDENTIFICATION/DATASET/README.md
  DRIVING BEHAVIOUR IDENTIFICATION/IMAGES/README.md
  DRIVING BEHAVIOUR IDENTIFICATION/MODEL/DRIVER BEHAVIOUR.ipynb
  DRIVING BEHAVIOUR IDENTIFICATION/MODEL/README.md
  DRIVING BEHAVIOUR IDENTIFICATION/REQUIRMENTS.txt
  README.md
Labels: Approved :white_check_mark:, SSOC 2022, Intermediate

#106 Issue 50: First Draft on Glass bangle Defect Detection
  Glass-Bangle-Defect-Detection/Datasets/README.md
  Glass-Bangle-Defect-Detection/Images/CNN model.png
  Glass-Bangle-Defect-Detection/Images/CNN-architecture-based-on-GoogLeNet-model.ppm.png
  Glass-Bangle-Defect-Detection/Images/GoogleNet-Validation.png
  Glass-Bangle-Defect-Detection/Images/GoogleNet-train.png
  Glass-Bangle-Defect-Detection/Images/ResNet-Validation.png
  Glass-Bangle-Defect-Detection/Images/ResNet-training.png
  Glass-Bangle-Defect-Detection/Images/Residual-Block.PNG
  Glass-Bangle-Defect-Detection/Model/Custom-Model.ipynb
  Glass-Bangle-Defect-Detection/Model/Glass-Bangle-Defect-Detection.ipynb
  Glass-Bangle-Defect-Detection/README.md
  Glass-Bangle-Defect-Detection/requirements.txt
Labels: Changes Requested

#117 Age and Sex Prediction #86
  Age and Sex Prediction/Dataset/README.md
  Age and Sex Prediction/Images/AccuracyforGender.png
  Age and Sex Prediction/Images/Age.png
  Age and Sex Prediction/Images/AgeDistribution.png
  Age and Sex Prediction/Images/DatasetPlot.png
  Age and Sex Prediction/Images/GenderDistribution.png
  Age and Sex Prediction/Images/ModelUsed.png
  Age and Sex Prediction/Images/ModelUsed2.png
  Age and Sex Prediction/Images/OneoftheDatasetImage.png
  Age and Sex Prediction/Images/genderloss.png
  Age and Sex Prediction/Images/test1.png
  Age and Sex Prediction/Images/test2.png
  Age and Sex Prediction/Images/test3.png
  Age and Sex Prediction/Model/Age&SexDetection2.ipynb
  Age and Sex Prediction/Model/Age_Sex_Prediction_DL.ipynb
  Age and Sex Prediction/Model/README.md
  Age and Sex Prediction/requirements.txt
Labels: Changes Requested

#127 Pseudo-Papilledema-Detection
  Pseudo-Papilledema-Detection/Dataset/README
  Pseudo-Papilledema-Detection/Images/1.png
  Pseudo-Papilledema-Detection/Images/2.png
  Pseudo-Papilledema-Detection/Images/3.png
  Pseudo-Papilledema-Detection/Images/4.png
  Pseudo-Papilledema-Detection/Images/5.png
  Pseudo-Papilledema-Detection/Images/6.png
  Pseudo-Papilledema-Detection/Model/notebook.ipynb
  Pseudo-Papilledema-Detection/README.md
  Pseudo-Papilledema-Detection/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Advanced

#133 Urdu Text Detection
  Urdu_Text_Detection/Dataset/README.md
  Urdu_Text_Detection/Images/CNN_architecture.png
  Urdu_Text_Detection/Images/adadelta_acc.png
  Urdu_Text_Detection/Images/adadelta_loss.png
  Urdu_Text_Detection/Images/adagrad_acc.png
  Urdu_Text_Detection/Images/adagrad_loss.png
  Urdu_Text_Detection/Images/adam_acc.png
  Urdu_Text_Detection/Images/adam_loss.png
  Urdu_Text_Detection/Images/aggregated_data.png
  Urdu_Text_Detection/Images/output_samples.png
  Urdu_Text_Detection/Images/performance_measure.png
  Urdu_Text_Detection/Images/sgd_acc.png
  Urdu_Text_Detection/Images/sgd_loss.png
  Urdu_Text_Detection/Images/testing_data.png
  Urdu_Text_Detection/Images/training_data.png
  Urdu_Text_Detection/Images/training_samples.png
  Urdu_Text_Detection/Model/README.md
  Urdu_Text_Detection/Model/urdu-text-detection.ipynb
  Urdu_Text_Detection/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Intermediate

#131 Google Recaptcha Image Classification
  Google Recaptcha Image Classification/Dataset/README.md
  Google Recaptcha Image Classification/Images/HyperparameterTestModel.png
  Google Recaptcha Image Classification/Images/bicycle.png
  Google Recaptcha Image Classification/Images/bridge.png
  Google Recaptcha Image Classification/Images/bus.png
  Google Recaptcha Image Classification/Images/car.png
  Google Recaptcha Image Classification/Images/chimney.png
  Google Recaptcha Image Classification/Images/crosswalk.png
  Google Recaptcha Image Classification/Images/hydrant.png
  Google Recaptcha Image Classification/Images/hyperparameterTestingTrainAccuracy.svg
  Google Recaptcha Image Classification/Images/hyperparameterTestingTrainLoss.svg
  Google Recaptcha Image Classification/Images/hyperparameterTestingValidationAccuracy.svg
  Google Recaptcha Image Classification/Images/hyperparameterTestingValidationLoss.svg
  Google Recaptcha Image Classification/Images/motorcycle.png
  Google Recaptcha Image Classification/Images/other.png
  Google Recaptcha Image Classification/Images/palm.png
  Google Recaptcha Image Classification/Images/stairs.png
  Google Recaptcha Image Classification/Images/trafficlight.png
  Google Recaptcha Image Classification/Model/GoogleRecaptcha.ipynb
  Google Recaptcha Image Classification/Model/README.md
  Google Recaptcha Image Classification/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Intermediate

#130 Adding the Railway Track Fault Detection Model
  Railway Track Fault Detection/Datasets/README.md
  Railway Track Fault Detection/Images/Images from Dataset.svg
  Railway Track Fault Detection/Images/Labels Count (In Each Data).svg
  Railway Track Fault Detection/Images/Labels Count Total.svg
  Railway Track Fault Detection/Images/Test Prediction Count.svg
  Railway Track Fault Detection/Images/Test Prediction Plot.svg
  Railway Track Fault Detection/Images/xception-performance.svg
  Railway Track Fault Detection/Model/README.md
  Railway Track Fault Detection/Model/Railway-Track-Fault-Detection.ipynb
  Railway Track Fault Detection/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Advanced

#137 Readme.md updated
  Fraudulent Transactions Detection/README.md
Labels: enhancement

#139 Quality Prediction in Mining Process
  Military Aircraft Detection/Datasets/README.md
  Military Aircraft Detection/Images/CNN-architecture-based-on-GoogLeNet-model.ppm.png
  Military Aircraft Detection/Images/EfficinetNet.png
  Military Aircraft Detection/Images/Residual-Block.PNG
  Military Aircraft Detection/Model/Military-Aircraft-Detection.ipynb
  Military Aircraft Detection/README.md
  Military Aircraft Detection/requirements.txt
  Quality Prediction in Mining Process/Dataset/README.md
  Quality Prediction in Mining Process/Images/eda 1.jpg
  Quality Prediction in Mining Process/Images/eda 2.jpg
  Quality Prediction in Mining Process/Images/iron mine.jpg
  Quality Prediction in Mining Process/Model/.ipynb_checkpoints/Quality Prediction in Mining Process-checkpoint.ipynb
  Quality Prediction in Mining Process/Model/quality-prediction-mining.ipynb
  Quality Prediction in Mining Process/README.md
  Quality Prediction in Mining Process/requirements.txt
Labels: Approved :white_check_mark:, SSOC 2022, Advanced

#134 Indian Food Recognition & Portuguese Meals Classification
  Indian Food Images Recognition/Dataset/README.md
  Indian Food Images Recognition/Images/model1_output.png
  Indian Food Images Recognition/Images/model2_output.png
  Indian Food Images Recognition/Images/model3_output.png
  Indian Food Images Recognition/Images/prediction.png
  Indian Food Images Recognition/Images/prediction2.png
  Indian Food Images Recognition/Images/visualize.png
  Indian Food Images Recognition/Models/Indian_Food_Classification.ipynb
  Indian Food Images Recognition/Models/README.md
  Indian Food Images Recognition/requirements.txt
  Portuguese Meals Classification/Dataset/README.md
  Portuguese Meals Classification/Images/output.png
  Portuguese Meals Classification/Images/prediction.png
  Portuguese Meals Classification/Images/prediction1.png
  Portuguese Meals Classification/Images/prediction2.png
  Portuguese Meals Classification/Images/visualise.png
  Portuguese Meals Classification/model/Portuguese_Meals_Detection.ipynb
  Portuguese Meals Classification/model/README.md
  Portuguese Meals Classification/requirements.txt
Labels: Changes Requested
