Repository abhisheks008/DL-Simplified, pull requests merged in 2023-12, with the labels that each got.

#379 Spam email detection
  Email Spam Classification/Datasets/Readme.md
  Email Spam Classification/Datasets/archive (3).zip
  Email Spam Classification/Images/Readme.md
  Email Spam Classification/Images/Screenshot (237).png
  Email Spam Classification/Images/Screenshot (238).png
  Email Spam Classification/Images/Screenshot (239).png
  Email Spam Classification/Images/Screenshot (240).png
  Email Spam Classification/Models/Readme.md
  Email Spam Classification/Models/email-spam-classification (1).ipynb
  Email Spam Classification/requirements.txt
Labels: status: approved, Level: Hard, Codepeak23

#381 Concrete Compressive Strength Prediction
  Concrete Compressive Strength/Dataset/Readme.md
  Concrete Compressive Strength/Dataset/archive (4).zip
  Concrete Compressive Strength/Images/Readme.md
  Concrete Compressive Strength/Images/Screenshot (243).png
  Concrete Compressive Strength/Images/Screenshot (244).png
  Concrete Compressive Strength/Models/Readme.Md
  Concrete Compressive Strength/Models/concrete-strength-dl (1).ipynb
  Concrete Compressive Strength/requirements.txt
Labels: Status: Approved, Level: Medium, Codepeak23

#384 Sea Animal Detection using Neural Networks
  Sea Animal Detection Using Neural Networks/Datasets/Readme.md
  Sea Animal Detection Using Neural Networks/Images/Screenshot (265).png
  Sea Animal Detection Using Neural Networks/Images/Screenshot (269).png
  Sea Animal Detection Using Neural Networks/Images/Screenshot (270).png
  Sea Animal Detection Using Neural Networks/Images/readme.md
  Sea Animal Detection Using Neural Networks/Models/Readme.md
  Sea Animal Detection Using Neural Networks/Models/cnn-sea-animal (1).ipynb
  Sea Animal Detection Using Neural Networks/requirements.txt
Labels: Status: Approved, Level: Medium, Codepeak23

#385 Twitter Sentiment Analysis using NLP
  Twitter Sentiment Analysis NLP/Dataset/Readme.md
  Twitter Sentiment Analysis NLP/Images/Readme.md
  Twitter Sentiment Analysis NLP/Images/Screenshot (275).png
  Twitter Sentiment Analysis NLP/Images/Screenshot (276).png
  Twitter Sentiment Analysis NLP/Images/Screenshot (277).png
  Twitter Sentiment Analysis NLP/Images/Screenshot (278).png
  Twitter Sentiment Analysis NLP/Images/Screenshot (279).png
  Twitter Sentiment Analysis NLP/Images/Screenshot (280).png
  Twitter Sentiment Analysis NLP/Models/Readme.Md
  Twitter Sentiment Analysis NLP/Models/sequential-mode.ipynb
  Twitter Sentiment Analysis NLP/Models/tweet_lstm.ipynb
  Twitter Sentiment Analysis NLP/Models/tweetbert.ipynb
  Twitter Sentiment Analysis NLP/requirements.txt
Labels: Status: Requested Changes

#387 Store Sales Prediction using Deep Learning
  Store Sales Prediction Using Deep Learning/Dataset/Readme.md
  Store Sales Prediction Using Deep Learning/Images/Readme.md
  Store Sales Prediction Using Deep Learning/Images/Screenshot (297).png
  Store Sales Prediction Using Deep Learning/Images/Screenshot (298).png
  Store Sales Prediction Using Deep Learning/Images/Screenshot (299).png
  Store Sales Prediction Using Deep Learning/Images/Screenshot (303).png
  Store Sales Prediction Using Deep Learning/Models/eda-for-sales.ipynb
  Store Sales Prediction Using Deep Learning/Models/ml-store-sales.ipynb
  Store Sales Prediction Using Deep Learning/Models/readme.md
  Store Sales Prediction Using Deep Learning/Models/store-sales-rnn.ipynb
  Store Sales Prediction Using Deep Learning/Requirements.txt
Labels: Status: Approved, Level: Hard, Codepeak23

#388 Disaster Twitter Sentiment Analysis using NLP
  Disaster Tweets Prediction using Deep Learning/Dataset/Readme.md
  Disaster Tweets Prediction using Deep Learning/Images/Readme.md
  Disaster Tweets Prediction using Deep Learning/Images/Screenshot (308).png
  Disaster Tweets Prediction using Deep Learning/Images/Screenshot (310).png
  Disaster Tweets Prediction using Deep Learning/Images/Screenshot (311).png
  Disaster Tweets Prediction using Deep Learning/Images/Screenshot (312).png
  Disaster Tweets Prediction using Deep Learning/Images/Screenshot (313).png
  Disaster Tweets Prediction using Deep Learning/Images/Screenshot (314).png
  Disaster Tweets Prediction using Deep Learning/Images/Screenshot (315).png
  Disaster Tweets Prediction using Deep Learning/Images/Screenshot (316).png
  Disaster Tweets Prediction using Deep Learning/Images/Screenshot (317).png
  Disaster Tweets Prediction using Deep Learning/Models/Readme.md
  Disaster Tweets Prediction using Deep Learning/Models/eda-disaster.ipynb
  Disaster Tweets Prediction using Deep Learning/Models/models-all.ipynb
  Disaster Tweets Prediction using Deep Learning/Models/transformer.ipynb
  Disaster Tweets Prediction using Deep Learning/requirements.txt
Labels: Status: Approved, Level: Hard, Codepeak23, Bonus Points

#389 Penguin and Turtle Image Classification Using DL
  Penguin and Turtle Image Classification using DL/Dataset/Readme.md
  Penguin and Turtle Image Classification using DL/Images/Readme.md
  Penguin and Turtle Image Classification using DL/Images/Screenshot (335).png
  Penguin and Turtle Image Classification using DL/Images/Screenshot (336).png
  Penguin and Turtle Image Classification using DL/Images/Screenshot (337).png
  Penguin and Turtle Image Classification using DL/Images/Screenshot (338).png
  Penguin and Turtle Image Classification using DL/Images/Screenshot (339).png
  Penguin and Turtle Image Classification using DL/Models/Readme.md
  Penguin and Turtle Image Classification using DL/Models/effecientnet.ipynb
  Penguin and Turtle Image Classification using DL/Models/resnet.ipynb
  Penguin and Turtle Image Classification using DL/requirements.txt
Labels: Status: Approved, Level: HARD, Codepeak23

#394 Heat sink defect detection
  Heat sink defect detection/dataset/README.md
  Heat sink defect detection/images/01.png
  Heat sink defect detection/images/02.png
  Heat sink defect detection/images/03.png
  Heat sink defect detection/images/04.png
  Heat sink defect detection/images/05.png
  Heat sink defect detection/images/06.png
  Heat sink defect detection/model/README.md
  Heat sink defect detection/model/model.ipynb
  Heat sink defect detection/requirements.txt
Labels: Status: Approved, Contributor

#391 Image Caption Generator
  Image Caption Generator/Dataset/Readme.md
  Image Caption Generator/Image/Screenshot from 2023-12-24 14-59-36.png
  Image Caption Generator/Image/Screenshot from 2023-12-24 15-59-25.png
  Image Caption Generator/Model/image_caption_generator.ipynb
  Image Caption Generator/Readme.md
  Image Caption Generator/requirements.txt
Labels: Status: Approved, Level: MEDIUM, Codepeak23

#392 MNIST Digit Classification using Neural Networks
  MNIST Digit Classification using Neural Networks/README.md
  MNIST Digit Classification using Neural Networks/bar graph.png
  MNIST Digit Classification using Neural Networks/dataset/readme.md
  MNIST Digit Classification using Neural Networks/histogram.png
  MNIST Digit Classification using Neural Networks/images/bar graph.png
  MNIST Digit Classification using Neural Networks/images/confusion matrix.png
  MNIST Digit Classification using Neural Networks/images/histogram.png
  MNIST Digit Classification using Neural Networks/images/input visualisation.png
  MNIST Digit Classification using Neural Networks/images/pie chart.png
  MNIST Digit Classification using Neural Networks/images/training loss.png
  MNIST Digit Classification using Neural Networks/input visualisation.png
  MNIST Digit Classification using Neural Networks/model/ANN_Handwritten_Digit_Classification.ipynb
  MNIST Digit Classification using Neural Networks/model/CNN_handwritten_digit_recogniser.ipynb
  MNIST Digit Classification using Neural Networks/pie chart.png
  MNIST Digit Classification using Neural Networks/requirement.txt
Labels: Status: Approved, Level: MEDIUM, Codepeak23

#397 Fake News Detection
  Fake News Detection/Dataset/README.md
  Fake News Detection/Images/Dataset.png
  Fake News Detection/Images/EDA.png
  Fake News Detection/Images/EDA1.png
  Fake News Detection/Images/metrics.png
  Fake News Detection/Images/model.png
  Fake News Detection/Images/model2.png
  Fake News Detection/Images/model2metrics.png
  Fake News Detection/Model/PridictionModel.ipynb
  Fake News Detection/README.md
Labels: Status: Approved, Level: MEDIUM, Codepeak23

#401 Flower Classification
  Flower Classification/Dataset/README.md
  Flower Classification/Images/EDA1.png
  Flower Classification/Images/EDA2.png
  Flower Classification/Images/EDA3.png
  Flower Classification/Images/lossandaccuracyplot.png
  Flower Classification/Images/lossplotForMobileNet.png
  Flower Classification/Images/output.png
  Flower Classification/Images/preprocessing.png
  Flower Classification/Images/train_dataset.png
  Flower Classification/Model/flower.webp
  Flower Classification/Model/label_map.json
  Flower Classification/Model/prediction.ipynb
  Flower Classification/README.md
Labels: Status: Approved, Level: HARD, Codepeak23

#398 Smile Recognition Using Deep Learning
  Smile Recognition with Deep Learning/Dataset/Readme.md
  Smile Recognition with Deep Learning/Images/Readme.md
  Smile Recognition with Deep Learning/Images/Screenshot (372).png
  Smile Recognition with Deep Learning/Images/cnn.png
  Smile Recognition with Deep Learning/Images/densenet.png
  Smile Recognition with Deep Learning/Images/test.png
  Smile Recognition with Deep Learning/Images/traing.png
  Smile Recognition with Deep Learning/Models/Readme.md
  Smile Recognition with Deep Learning/Models/cnn-smile.ipynb
  Smile Recognition with Deep Learning/Models/densenet.ipynb
  Smile Recognition with Deep Learning/requirements.txt
Labels: Status: Approved, Level: MEDIUM, Codepeak23

#403 Lung Cancer Detection Using 10 Models
  Lung Cancer Detection/Dataset/readme.md
  Lung Cancer Detection/Images/Readme.md
  Lung Cancer Detection/Images/Screenshot (379).png
  Lung Cancer Detection/Images/Screenshot (381).png
  Lung Cancer Detection/Images/Screenshot (382).png
  Lung Cancer Detection/Images/Screenshot (383).png
  Lung Cancer Detection/Images/Screenshot (384).png
  Lung Cancer Detection/Models/Readme.md
  Lung Cancer Detection/Models/ml-all.ipynb
  Lung Cancer Detection/Models/sequential.ipynb
  Lung Cancer Detection/requirements.txt
Labels: Status: Approved, Level: MEDIUM, Codepeak23

#405 Ship Classification Using Deep Learning
  Ship Classification Using Deep Learning/Dataset/Readme.md
  Ship Classification Using Deep Learning/Images/Screenshot (386).png
  Ship Classification Using Deep Learning/Images/Screenshot (388).png
  Ship Classification Using Deep Learning/Images/Screenshot (389).png
  Ship Classification Using Deep Learning/Images/mlf.png
  Ship Classification Using Deep Learning/Images/readme.md
  Ship Classification Using Deep Learning/Models/Readme.md
  Ship Classification Using Deep Learning/Models/Screenshot (387).png
  Ship Classification Using Deep Learning/Models/densenet.ipynb
  Ship Classification Using Deep Learning/Models/vcgnet.ipynb
  Ship Classification Using Deep Learning/Models/xception-for-ship-classification.ipynb
  Ship Classification Using Deep Learning/requirements.txt
Labels: Status: Approved, Level: HARD, Codepeak23, BONUS

#407 Wine Reviews Classification
  Wine Reviews Classification/Dataset/README.md
  Wine Reviews Classification/Images/Accuracy_Model1.png
  Wine Reviews Classification/Images/Accuracy_Model2.png
  Wine Reviews Classification/Images/EDA1.png
  Wine Reviews Classification/Images/EDA2.png
  Wine Reviews Classification/Images/EDA3.png
  Wine Reviews Classification/Images/Input_Dataset.png
  Wine Reviews Classification/Images/Model1.png
  Wine Reviews Classification/Images/Model2.png
  Wine Reviews Classification/Model/PridictionModel.ipynb
  Wine Reviews Classification/README.md
Labels: Status: Approved, Level: MEDIUM, Codepeak23

#408 Weed Classification
  Weed Classification/Dataset/README.md
  Weed Classification/Images/Accuracy.png
  Weed Classification/Images/Confusion-Matrix.png
  Weed Classification/Images/EDA1.png
  Weed Classification/Images/Input.png
  Weed Classification/Images/Metrics.png
  Weed Classification/Images/Model-1.png
  Weed Classification/Images/Model-2.png
  Weed Classification/Images/Output_Classes.png
  Weed Classification/Model/weed-classification.ipynb
  Weed Classification/README.md
Labels: Status: Approved, Level: MEDIUM, Codepeak23
