Repository abhisheks008/DL-Simplified, pull requests merged in 2023-07, with the labels that each got.

#320 Cats vs Dogs Audio Classification using DL
  Cats vs Dogs Audio Classification using DL/Dataset/README.md
  Cats vs Dogs Audio Classification using DL/Images/cnn.png
  Cats vs Dogs Audio Classification using DL/Images/mobilenetv2.png
  Cats vs Dogs Audio Classification using DL/Images/resnet50.png
  Cats vs Dogs Audio Classification using DL/Images/spectograms.png
  Cats vs Dogs Audio Classification using DL/Images/vgg16.png
  Cats vs Dogs Audio Classification using DL/Model/Cats vs Dogs Audio Classification.ipynb
  Cats vs Dogs Audio Classification using DL/README.md
  Cats vs Dogs Audio Classification using DL/Requirements.txt
Labels: status: approved, SSOC, level: intermediate

#323 Distracted Driver Detection using DL
  Distracted Driver Detection/Dataset/README.md
  Distracted Driver Detection/Images/Xception.png
  Distracted Driver Detection/Images/cnn.png
  Distracted Driver Detection/Images/inception.png
  Distracted Driver Detection/Images/testdist.png
  Distracted Driver Detection/Images/traindist.png
  Distracted Driver Detection/Images/vgg16.png
  Distracted Driver Detection/Model/Distracted Driver Detection using DL.ipynb
  Distracted Driver Detection/Model/README.md
  Distracted Driver Detection/Requirements.txt
Labels: status: approved, SSOC, level: intermediate, points: updated

#322 Staircases Segmentation Using DL Issue #217
  Staircases Segmentation Using DL/Dataset/Readme.md
  Staircases Segmentation Using DL/Images/Confusion Matrix InceptionV3.jpg
  Staircases Segmentation Using DL/Images/Confusion Matrix Mobilenet.jpg
  Staircases Segmentation Using DL/Images/Confusion Matrix VGG16.jpg
  Staircases Segmentation Using DL/Images/InceptionV3_ACC graph.jpg
  Staircases Segmentation Using DL/Images/InceptionV3_loss_graph.jpg
  Staircases Segmentation Using DL/Images/Mobilenet_acc_curve .png
  Staircases Segmentation Using DL/Images/Mobilenet_loss_Curve.jpg
  Staircases Segmentation Using DL/Images/VGG16_acc_curve.jpg
  Staircases Segmentation Using DL/Images/VGG16_loss_curve.jpg
  Staircases Segmentation Using DL/Images/Xception_acc_graph.jpg
  Staircases Segmentation Using DL/Images/Xception_confusion_matrix.jpg
  Staircases Segmentation Using DL/Images/Xception_loss_curve.jpg
  Staircases Segmentation Using DL/Model/Readme.md
  Staircases Segmentation Using DL/Model/Stair_Segmentation_Model_2_MobileNet.ipynb
  Staircases Segmentation Using DL/Model/Stair_Segmentation_Model_3_InceptionV3.ipynb
  Staircases Segmentation Using DL/Model/Stair_Segmentation_Model_4_xception.ipynb
  Staircases Segmentation Using DL/Model/Stair__Segmentation_Model_1_VGG16.ipynb
  Staircases Segmentation Using DL/Requirements.txt
Labels: status: approved, SSOC, level: intermediate, points: updated

#332 Anti Spoofing Project using DL
  Anti Spoofing Project using DL/Dataset/README.md
  Anti Spoofing Project using DL/Images/Screen Shot 2023-07-06 at 00.32.23.png
  Anti Spoofing Project using DL/Images/Screen Shot 2023-07-06 at 00.32.39.png
  Anti Spoofing Project using DL/Images/Screen Shot 2023-07-06 at 00.32.57.png
  Anti Spoofing Project using DL/Images/Screen Shot 2023-07-06 at 00.34.00.png
  Anti Spoofing Project using DL/Images/Screen Shot 2023-07-06 at 00.34.21.png
  Anti Spoofing Project using DL/Images/Screen Shot 2023-07-06 at 00.34.48.png
  Anti Spoofing Project using DL/Images/Screen Shot 2023-07-06 at 00.35.09.png
  Anti Spoofing Project using DL/Images/Screen Shot 2023-07-06 at 00.35.27.png
  Anti Spoofing Project using DL/Model/README.md
  Anti Spoofing Project using DL/Model/anti-spoofing-project-using-dl.ipynb
  Anti Spoofing Project using DL/requirements.txt
Labels: status: approved, SSOC, level: intermediate

#330 Musical Instrument Chord Classification
  Musical Instrument Chord Classification/Dataset/README.md
  Musical Instrument Chord Classification/Images/ann.png
  Musical Instrument Chord Classification/Images/cnn.png
  Musical Instrument Chord Classification/Images/mlp.png
  Musical Instrument Chord Classification/Images/onechannel.png
  Musical Instrument Chord Classification/Images/twochannel.png
  Musical Instrument Chord Classification/Model/Musical Instrument Chord Classification.ipynb
  Musical Instrument Chord Classification/README.md
  Musical Instrument Chord Classification/Requirements.txt
Labels: status: approved, SSOC, level: intermediate, points: updated

#333 Emergency Fire detection
  Emergency Fire detection/Dataset/Readme.md
  Emergency Fire detection/Images/001_FireDetectionCNN.png
  Emergency Fire detection/Images/002_FireDetectionCNN.png
  Emergency Fire detection/Images/003_FireDetectionCNN.PNG
  Emergency Fire detection/Images/004_InceptionFireDetection.png
  Emergency Fire detection/Images/005_InceptionFireDetection.png
  Emergency Fire detection/Images/006_InceptionFireDetection.PNG
  Emergency Fire detection/Model/FireDetectionCNN.ipynb
  Emergency Fire detection/Model/InceptionFireDetection.ipynb
  Emergency Fire detection/Model/Readme.md
  Emergency Fire detection/requirements.txt
Labels: status: approved, SSOC, level: intermediate, points: updated

#336 Gender Classification using DL
  Gender Classification using DL/Dataset/README.md
  Gender Classification using DL/Images/aug1.png
  Gender Classification using DL/Images/aug2.png
  Gender Classification using DL/Images/aug3.png
  Gender Classification using DL/Images/aug4.png
  Gender Classification using DL/Images/comparision.png
  Gender Classification using DL/Images/inception.png
  Gender Classification using DL/Images/mobilenet.png
  Gender Classification using DL/Images/pred1.png
  Gender Classification using DL/Images/pred2.png
  Gender Classification using DL/Images/resnet50.png
  Gender Classification using DL/Images/vgg16.png
  Gender Classification using DL/Model/Gender Classification using DL.ipynb
  Gender Classification using DL/README.md
  Gender Classification using DL/Requirements.txt
Labels: status: approved, SSOC, level: intermediate, points: updated

#341 Weather Image Recognition
  Weather Image Recognition/README.md
  Weather Image Recognition/dataset/readme.md
  Weather Image Recognition/images/classification report (InceptionV3).png
  Weather Image Recognition/images/classification report (ResNet152v2).png
  Weather Image Recognition/images/classification report (VGG19).png
  Weather Image Recognition/images/predict_labels.png
  Weather Image Recognition/images/readme.md
  Weather Image Recognition/models/InceptionV3(88%).ipynb
  Weather Image Recognition/models/ResNet152V2(94%).ipynb
  Weather Image Recognition/models/VGG19(91%).ipynb
  Weather Image Recognition/models/readme.md
Labels: status: approved, SSOC, level: intermediate, points: updated

#348 Mushroom Classification using Deep Neural Networks
  Mushroom Classification using Deep Learning/Dataset/Readme.md
  Mushroom Classification using Deep Learning/Images/cnn stats.png
  Mushroom Classification using Deep Learning/Images/image visualization for mushroom classes.png
  Mushroom Classification using Deep Learning/Images/indep stats.png
  Mushroom Classification using Deep Learning/Images/predictions.png
  Mushroom Classification using Deep Learning/Model/Classification using EfficientNet50.ipynb
  Mushroom Classification using Deep Learning/Model/Classification using InceptionV3.ipynb
  Mushroom Classification using Deep Learning/Model/Classification using Torch.ipynb
  Mushroom Classification using Deep Learning/Readme.md
  Mushroom Classification using Deep Learning/conv.py
Labels: good first issue, status: approved, SSOC, level: intermediate

#351 Ship Detection from Aerial Images
  Ship Detection from Aerial Images/Dataset/README.md
  Ship Detection from Aerial Images/Images/yolo5x_confusion_matrix.png
  Ship Detection from Aerial Images/Images/yolo5x_results.png
  Ship Detection from Aerial Images/Images/yolo5x_val_pred.jpg
  Ship Detection from Aerial Images/Images/yolo_v8results.png
  Ship Detection from Aerial Images/Images/yolov5m_confusion_matrix.png
  Ship Detection from Aerial Images/Images/yolov5m_results.png
  Ship Detection from Aerial Images/Images/yolov5s_confusion_matrix.png
  Ship Detection from Aerial Images/Images/yolov5s_results.png
  Ship Detection from Aerial Images/Images/yolov5s_val_pred.jpg
  Ship Detection from Aerial Images/Images/yolov8_confusion_matrix.png
  Ship Detection from Aerial Images/Images/yolov8_val_pred.jpg
  Ship Detection from Aerial Images/Model/Ship Detection using YOLOv5.ipynb
  Ship Detection from Aerial Images/Model/Ship Detection using YOLOv8.ipynb
  Ship Detection from Aerial Images/Model/custom_data_ship.yaml
  Ship Detection from Aerial Images/README.md
Labels: good first issue, status: approved, SSOC, level: intermediate

#354 Chocolate Classification using DL
  Chocolate Classification using DL/Dataset/README.md
  Chocolate Classification using DL/Images/acc_cnn.jpg
  Chocolate Classification using DL/Images/acc_resnet50.jpg
  Chocolate Classification using DL/Images/acc_vgg16.jpg
  Chocolate Classification using DL/Images/dist.png
  Chocolate Classification using DL/Images/loss_cnn.jpg
  Chocolate Classification using DL/Images/loss_resnet50.jpg
  Chocolate Classification using DL/Images/loss_vgg16.jpg
  Chocolate Classification using DL/Model/Chocolate Classification using DL.ipynb
  Chocolate Classification using DL/README.md
  Chocolate Classification using DL/Requirements.txt
Labels: good first issue, status: approved, SSOC, level: intermediate, points: updated

#358 Honey Bee Pollen Detection
  Honey Bee Pollen detection/Dataset/readme.md
  Honey Bee Pollen detection/Images/CNN Comparison evaluation.png
  Honey Bee Pollen detection/Images/Comparison Graph.png
  Honey Bee Pollen detection/Images/DenseNet Compariosn evaluation.png
  Honey Bee Pollen detection/Images/VGG16 Comparison evaluation.png
  Honey Bee Pollen detection/Images/readme.md
  Honey Bee Pollen detection/Models/CNN.ipynb
  Honey Bee Pollen detection/Models/DenseNet.ipynb
  Honey Bee Pollen detection/Models/VGG16.ipynb
  Honey Bee Pollen detection/Models/readme.md
  Honey Bee Pollen detection/Models/requirement.text
  Honey Bee Pollen detection/README.md
Labels: good first issue, status: approved, SSOC, level: intermediate, points: updated

#360 Scene Classification using DL
  Scene Classification using DL/Dataset/README.md
  Scene Classification using DL/Images/cnn.png
  Scene Classification using DL/Images/dist.png
  Scene Classification using DL/Images/resnet50.png
  Scene Classification using DL/Images/vgg16.png
  Scene Classification using DL/Model/Scene Classification using DL.ipynb
  Scene Classification using DL/README.md
  Scene Classification using DL/Requirements.txt
Labels: good first issue, status: approved, SSOC, level: intermediate, points: updated

#362 Avocados classification
  Avocados Classification/Dataset/readme.md
  Avocados Classification/Images/Comparison graph...png
  Avocados Classification/Images/FNN Comparison evaluation.png
  Avocados Classification/Images/LSTM comparison evaluation.png
  Avocados Classification/Images/TabNet Comparison evaluation.png
  Avocados Classification/Images/readme.md
  Avocados Classification/Models/FNN.ipynb
  Avocados Classification/Models/LSTM.ipynb
  Avocados Classification/Models/TabNet.ipynb
  Avocados Classification/Models/readme.md
  Avocados Classification/Models/requirement.text
  Avocados Classification/README.md
Labels: good first issue, status: approved, SSOC, level: intermediate, points: updated

#350 Market Basket Analysis
  Market Basket Analysis/Dataset/basket_analysis.csv
  Market Basket Analysis/Images/Association Rules - Apriori.png
  Market Basket Analysis/Images/Association Rules - FP Growth.png
  Market Basket Analysis/Images/Comparison Results.png
  Market Basket Analysis/Images/Comparison.png
  Market Basket Analysis/Images/Dataset.png
  Market Basket Analysis/Model/Market_Basket_Analysis.ipynb
  Market Basket Analysis/Model/market_basket_analysis.py
  Market Basket Analysis/readme.md
  Market Basket Analysis/requirements.txt
Labels: good first issue, status: approved, SSOC, level: intermediate, points: updated

#364 Maize Leave Disease Detection
  Maize Leave Disease Detection/README.md
  Maize Leave Disease Detection/dataset/readme.md
  Maize Leave Disease Detection/images/readme.md
  Maize Leave Disease Detection/models/Maize(InceptionV3-88%).ipynb
  Maize Leave Disease Detection/models/Maize(mobilnet-91%).ipynb
  Maize Leave Disease Detection/models/Maize(vgg16-91%).ipynb
  Maize Leave Disease Detection/models/Maize(vgg19-88%).ipynb
  Maize Leave Disease Detection/models/readme.md
Labels: good first issue, status: approved, SSOC, level: intermediate, points: updated

#366 Earthquake Type Prediction
  Earthquake Type Prediction/Dataset/readme.md
  Earthquake Type Prediction/Images/BRNN comparison evalutaion.png
  Earthquake Type Prediction/Images/Comparison Graph....png
  Earthquake Type Prediction/Images/FNN comparison evaluation.png
  Earthquake Type Prediction/Images/GRU comparison evaluation.png
  Earthquake Type Prediction/Models/BRNN.ipynb
  Earthquake Type Prediction/Models/FNN.ipynb
  Earthquake Type Prediction/Models/GRU.ipynb
  Earthquake Type Prediction/Models/Readme.md
  Earthquake Type Prediction/Models/requirement.txt
  Earthquake Type Prediction/README.md
Labels: status: requested changes, SSOC

#368 Colour Detection using DL
  Colour Detection using DL/Dataset/README.md
  Colour Detection using DL/Images/cnn 2.jpg
  Colour Detection using DL/Images/cnn.jpg
  Colour Detection using DL/Images/res 2.jpg
  Colour Detection using DL/Images/res.jpg
  Colour Detection using DL/Images/vgg16 2.jpg
  Colour Detection using DL/Images/vgg16.jpg
  Colour Detection using DL/Model/Colour Detection using DL.ipynb
  Colour Detection using DL/README.md
  Colour Detection using DL/Requirements.txt
Labels: good first issue, status: approved, SSOC, level: intermediate, points: updated

#371 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, status: approved, SSOC, level: beginner
