Repository abhisheks008/DL-Simplified, pull requests merged in 2023-06, with the labels that each got.

#255 Lemon Quality Segmentation #216
  Lemon Quality Segmentation/Dataset/readme.md
  Lemon Quality Segmentation/Images/Accuracy Evaluation.png
  Lemon Quality Segmentation/Images/predicted labels .png
  Lemon Quality Segmentation/Images/readme.md
  Lemon Quality Segmentation/Images/training and validation metrics (AexNet).png
  Lemon Quality Segmentation/Images/training and validation metrics (VGG16).png
  Lemon Quality Segmentation/Images/training and validation metrics (simpleCNN).png
  Lemon Quality Segmentation/Models/AlexNet(99.6% acc.).ipynb
  Lemon Quality Segmentation/Models/VGG16(98.5% acc.).ipynb
  Lemon Quality Segmentation/Models/comparison.ipynb
  Lemon Quality Segmentation/Models/readme.md
  Lemon Quality Segmentation/Models/simple-cnn-(99% acc).ipynb
  Lemon Quality Segmentation/README.md
  Lemon Quality Segmentation/requirements.txt
Labels: status: approved, SSOC

#261 Pull Request for Children vs Adults Classification using DL #210
  Children vs Adults Classification using DL/Dataset/README.md
  Children vs Adults Classification using DL/Images/comparison1.png
  Children vs Adults Classification using DL/Images/comparison2.png
  Children vs Adults Classification using DL/Model/Children vs Adult Classification.ipynb
  Children vs Adults Classification using DL/Model/README.md
  Children vs Adults Classification using DL/requirements.txt
Labels: status: approved, SSOC, level: intermediate

#262 Added PII Document Classification model
  PII Doc Classification using Transfer Learning/Dataset/README.md
  PII Doc Classification using Transfer Learning/Images/Accuracy1.png
  PII Doc Classification using Transfer Learning/Images/Accuracy2.png
  PII Doc Classification using Transfer Learning/Images/Loss1.png
  PII Doc Classification using Transfer Learning/Images/Loss2.png
  PII Doc Classification using Transfer Learning/Model/PII Documents Classification.ipynb
  PII Doc Classification using Transfer Learning/Model/README.md
  PII Doc Classification using Transfer Learning/requirements.txt
Labels: status: approved, SSOC, level: intermediate

#271 Pull Request for Electron Microscopy Particle Segmentation #234
  Electron Microscope Particle Segmentation/Dataset/README.md
  Electron Microscope Particle Segmentation/Images/output.png
  Electron Microscope Particle Segmentation/Images/output1.png
  Electron Microscope Particle Segmentation/Images/output2.png
  Electron Microscope Particle Segmentation/Images/output3.png
  Electron Microscope Particle Segmentation/Model/Electron Microscopy Particle Segmentation using UNet.ipynb
  Electron Microscope Particle Segmentation/Model/Electron Microscopy Particle Segmentation.ipynb
  Electron Microscope Particle Segmentation/Model/README.md
  Electron Microscope Particle Segmentation/requirements.txt
Labels: status: approved, SSOC, level: intermediate

#277 Predict the Time of the Day using DL
  Predict the Time of the Day using DL/Dataset/README.md
  Predict the Time of the Day using DL/Images/IMG_4633.jpeg
  Predict the Time of the Day using DL/Images/IMG_4634.jpeg
  Predict the Time of the Day using DL/Images/IMG_4635.jpeg
  Predict the Time of the Day using DL/Images/IMG_4636.jpeg
  Predict the Time of the Day using DL/Images/IMG_4637.jpeg
  Predict the Time of the Day using DL/Images/IMG_4638.jpeg
  Predict the Time of the Day using DL/Images/IMG_4639.jpeg
  Predict the Time of the Day using DL/Images/IMG_4640.jpeg
  Predict the Time of the Day using DL/Images/IMG_4641.jpeg
  Predict the Time of the Day using DL/Images/IMG_4642.jpeg
  Predict the Time of the Day using DL/Images/IMG_4643.jpeg
  Predict the Time of the Day using DL/Images/IMG_4644.jpeg
  Predict the Time of the Day using DL/Images/IMG_4645.jpeg
  Predict the Time of the Day using DL/Images/README.md
  Predict the Time of the Day using DL/Model/README.md
  Predict the Time of the Day using DL/Model/main-code.ipynb
  Predict the Time of the Day using DL/requirement.txt
Labels: status: requested changes, SSOC

#281 Pull Request for Tweet Analysis of Indian Political Parties
  Tweet Analysis of Political Parties/Dataset/README.md
  Tweet Analysis of Political Parties/Images/aap_roberta.png
  Tweet Analysis of Political Parties/Images/aap_tweets_monthwise.png
  Tweet Analysis of Political Parties/Images/aap_tweets_monthwise_2023.png
  Tweet Analysis of Political Parties/Images/aap_tweets_yearwise.png
  Tweet Analysis of Political Parties/Images/aap_vader.png
  Tweet Analysis of Political Parties/Images/aap_vader_hist.png
  Tweet Analysis of Political Parties/Images/aap_vader_vs_roberta.png
  Tweet Analysis of Political Parties/Images/app_comp_line.png
  Tweet Analysis of Political Parties/Images/bjp4india_comp_line.png
  Tweet Analysis of Political Parties/Images/bjp4india_roberta.png
  Tweet Analysis of Political Parties/Images/bjp4india_tweets_monthwise.png
  Tweet Analysis of Political Parties/Images/bjp4india_tweets_monthwise_2023.png
  Tweet Analysis of Political Parties/Images/bjp4india_tweets_yearwise.png
  Tweet Analysis of Political Parties/Images/bjp4india_vader_hist.png
  Tweet Analysis of Political Parties/Images/bjp4india_vader_vs_roberta.png
  Tweet Analysis of Political Parties/Images/bjp4inida_vader.png
  Tweet Analysis of Political Parties/Images/final_comppng.png
  Tweet Analysis of Political Parties/Model/AamAadmiParty.ipynb
  Tweet Analysis of Political Parties/Model/BJP4India.ipynb
  Tweet Analysis of Political Parties/Model/INCIndia.ipynb
  Tweet Analysis of Political Parties/Model/README.md
  Tweet Analysis of Political Parties/requirements.txt
Labels: status: approved, SSOC, level: intermediate

#283 Smartphone processor classification
  Smartphone processor classification/Images/Matrix model 1.png
  Smartphone processor classification/Images/Matrix model 2.png
  Smartphone processor classification/Images/Visualization model 1.png
  Smartphone processor classification/Images/Visualization model 2.png
  Smartphone processor classification/Images/Visualization model 3.png
  Smartphone processor classification/Images/matrix model 3.png
  Smartphone processor classification/dataset/ML_ALL_benchmarks.csv
  Smartphone processor classification/dataset/antutu_android_vs_ios_v4.csv
  Smartphone processor classification/dataset/smartphone_cpu_stats.csv
  Smartphone processor classification/model/ML_ALL_benchmarks.csv
  Smartphone processor classification/model/Ranking.ipynb
  Smartphone processor classification/readme.md
  Smartphone processor classification/requirements.txt
Labels: status: approved, SSOC, level: intermediate

#287 Pull Request for Sephora Products and Skincare Reviews using NLP #265
  Sephora Products and Skincare Reviews using NLP/Dataset/README.md
  Sephora Products and Skincare Reviews using NLP/Images/is_recommended.png
  Sephora Products and Skincare Reviews using NLP/Images/ratings.png
  Sephora Products and Skincare Reviews using NLP/Images/top10_products_lovecount.png
  Sephora Products and Skincare Reviews using NLP/Images/top10_products_reviews.png
  Sephora Products and Skincare Reviews using NLP/Images/wordcloud.png
  Sephora Products and Skincare Reviews using NLP/Images/wordcloud2.png
  Sephora Products and Skincare Reviews using NLP/Images/yearwise_reviews.png
  Sephora Products and Skincare Reviews using NLP/Model/README.md
  Sephora Products and Skincare Reviews using NLP/Model/Sephora Products and Skincare Reviews using NLP.ipynb
  Sephora Products and Skincare Reviews using NLP/Requirements.txt
Labels: status: approved, SSOC, level: intermediate, points: updated

#289 Vegetable Image Classification
  Vegetable Image Classification/Dataset/readme.md
  Vegetable Image Classification/Images/MobileNet.png
  Vegetable Image Classification/Images/ResNet50V2.png
  Vegetable Image Classification/Images/accuracy evaluation.png
  Vegetable Image Classification/Images/predicted labels.png
  Vegetable Image Classification/Images/readme.md
  Vegetable Image Classification/Images/simpleCNN.png
  Vegetable Image Classification/Models/MobileNet(99.4%).ipynb
  Vegetable Image Classification/Models/ResNet50V2(98%).ipynb
  Vegetable Image Classification/Models/SimpleCNN(96.2%).ipynb
  Vegetable Image Classification/Models/comparison.ipynb
  Vegetable Image Classification/Models/readme.md
  Vegetable Image Classification/README.md
Labels: status: approved, SSOC, level: intermediate

#296 Pull Request for Hand Gloves Detection using DL
  Hand Gloves Detection using DL/Dataset/README.md
  Hand Gloves Detection using DL/Images/cnn.png
  Hand Gloves Detection using DL/Images/img1.png
  Hand Gloves Detection using DL/Images/img2.png
  Hand Gloves Detection using DL/Images/inception.png
  Hand Gloves Detection using DL/Images/vgg16.png
  Hand Gloves Detection using DL/Images/xception.png
  Hand Gloves Detection using DL/Model/Hand Gloves Detection using DL.ipynb
  Hand Gloves Detection using DL/Model/README.md
  Hand Gloves Detection using DL/Requirements.txt
Labels: status: approved, SSOC, level: intermediate, points: updated

#301 Pull Request for Cats vs Dogs Classification using DL
  Cats vs Dogs Classification using DL/Dataset/README.md
  Cats vs Dogs Classification using DL/Images/val_acc1.JPG
  Cats vs Dogs Classification using DL/Images/val_acc2.JPG
  Cats vs Dogs Classification using DL/Images/val_acc3.JPG
  Cats vs Dogs Classification using DL/Images/val_loss1.JPG
  Cats vs Dogs Classification using DL/Images/val_loss2.JPG
  Cats vs Dogs Classification using DL/Images/val_loss3.JPG
  Cats vs Dogs Classification using DL/Model/Cats vs Dogs Classification using DL.ipynb
  Cats vs Dogs Classification using DL/README.md
  Cats vs Dogs Classification using DL/Requirements.txt
Labels: status: approved, SSOC, level: intermediate, points: updated

#303 Toxic Comment Classification
  Toxic Comment Classification/Dataset/README.md
  Toxic Comment Classification/Images/bar.png
  Toxic Comment Classification/Images/blstm.png
  Toxic Comment Classification/Images/cnn.png
  Toxic Comment Classification/Images/lstm.png
  Toxic Comment Classification/Images/pie.png
  Toxic Comment Classification/Model/README.md
  Toxic Comment Classification/Model/Toxic Comment Classification.ipynb
  Toxic Comment Classification/Requirements.txt
Labels: status: approved, SSOC, level: intermediate

#307 STROKE PREDICTION
  Stroke Prediction/Dataset/Readme.md
  Stroke Prediction/Images/ANN Comparison evaluation.png
  Stroke Prediction/Images/Comparison graph.png
  Stroke Prediction/Images/FNN Comparison evaluation.png
  Stroke Prediction/Images/RNN Comparison evaluation.png
  Stroke Prediction/Images/Readme.md
  Stroke Prediction/Models/ANN.ipynb
  Stroke Prediction/Models/FNN.ipynb
  Stroke Prediction/Models/RNN.ipynb
  Stroke Prediction/Models/Readme.md
  Stroke Prediction/Models/requirements.text
  Stroke Prediction/README.md
Labels: status: approved, SSOC, level: intermediate

#308 Pneumonia Detection using X-Ray
  Pneumonia Detection using X-Ray Images/Dataset/Readme.md
  Pneumonia Detection using X-Ray Images/Images/Accuracy Graph CNN.png
  Pneumonia Detection using X-Ray Images/Images/Accuracy Graph Efficientnet50.png
  Pneumonia Detection using X-Ray Images/Images/CNN Result.png
  Pneumonia Detection using X-Ray Images/Images/Grayscale visuals.png
  Pneumonia Detection using X-Ray Images/Images/Loss Graph CNN.png
  Pneumonia Detection using X-Ray Images/Images/Loss Graph EfficientNet50.png
  Pneumonia Detection using X-Ray Images/Images/Matshow Image.png
  Pneumonia Detection using X-Ray Images/Models/Pneumonia Detection using X-Ray Images.ipynb
  Pneumonia Detection using X-Ray Images/Models/Pneumonia Detection via CNN.ipynb
  Pneumonia Detection using X-Ray Images/Readme.md
Labels: status: approved, SSOC, level: intermediate

#298 Face Mask Detection
  Face Mask Detection/Dataset/Readme.md
  Face Mask Detection/Images/Distribution of classes.jpg
  Face Mask Detection/Images/Evaluation.jpg
  Face Mask Detection/Images/Readme.md
  Face Mask Detection/Images/Sample Images.jpg
  Face Mask Detection/Model/Readme.md
  Face Mask Detection/Model/detecting-face-masks-with-5-models.ipynb
  Face Mask Detection/requirements.txt
Labels: status: approved, SSOC, level: advanced

#309 Scientific Research Article Topic Classification
  Scientific Research Article Topic Classification/Dataset/README.md
  Scientific Research Article Topic Classification/Images/bar.png
  Scientific Research Article Topic Classification/Images/bilstm.png
  Scientific Research Article Topic Classification/Images/cnn.png
  Scientific Research Article Topic Classification/Images/lstm.png
  Scientific Research Article Topic Classification/Images/pie.png
  Scientific Research Article Topic Classification/Model/README.md
  Scientific Research Article Topic Classification/Model/Scientific Research Article Topic Classification.ipynb
  Scientific Research Article Topic Classification/Requirements.txt
Labels: status: approved, SSOC, level: intermediate, points: updated

#311 Dog Breeds Classification
  Dog Breeds Classification/Dataset/readme.md
  Dog Breeds Classification/Images/Accuracy Evaluation.png
  Dog Breeds Classification/Images/MobileNet.png
  Dog Breeds Classification/Images/ResNet50v2.png
  Dog Breeds Classification/Images/VGG19.png
  Dog Breeds Classification/Images/predicted labels.png
  Dog Breeds Classification/Images/readme.md
  Dog Breeds Classification/Models/MobileNet(96%).ipynb
  Dog Breeds Classification/Models/ResNet50v2(98%).ipynb
  Dog Breeds Classification/Models/Vgg19(91%).ipynb
  Dog Breeds Classification/Models/comparison_of_models.ipynb
  Dog Breeds Classification/Models/readme.md
  Dog Breeds Classification/README.md
Labels: status: approved, SSOC, level: intermediate

#313 Crack Detection using DL
  Crack Detection using DL/Dataset/README.md
  Crack Detection using DL/Images/image.png
  Crack Detection using DL/Images/inceptionv3.png
  Crack Detection using DL/Images/negatives.png
  Crack Detection using DL/Images/positives.png
  Crack Detection using DL/Images/resnet50.png
  Crack Detection using DL/Images/vgg16.png
  Crack Detection using DL/Model/Crack Detection using DL.ipynb
  Crack Detection using DL/Model/README.md
  Crack Detection using DL/Requirements.txt
Labels: status: approved, SSOC, level: intermediate

#316 Leukaemia Classification using DL
  Leukaemia Classification using DL/Dataset/README.md
  Leukaemia Classification using DL/Images/cnn.png
  Leukaemia Classification using DL/Images/demo1.png
  Leukaemia Classification using DL/Images/demo2.png
  Leukaemia Classification using DL/Images/demo3.png
  Leukaemia Classification using DL/Images/exception.png
  Leukaemia Classification using DL/Images/inception.png
  Leukaemia Classification using DL/Images/resnet50.png
  Leukaemia Classification using DL/Images/vgg16.png
  Leukaemia Classification using DL/Model/Leukaemia Classification using DL.ipynb
  Leukaemia Classification using DL/README.md
  Leukaemia Classification using DL/Requirements.txt
Labels: status: requested changes, SSOC
