Repository abhisheks008/DL-Simplified, pull requests merged in 2024-11, with the labels that each got.

#962 GAN-based Art Generator using Deep learning
  GAN-based Art Generator using Deep learning/Dataset/README.md
  GAN-based Art Generator using Deep learning/Images/Image 1.png
  GAN-based Art Generator using Deep learning/Images/Image 2.png
  GAN-based Art Generator using Deep learning/Images/Image 3.png
  GAN-based Art Generator using Deep learning/Images/Image 4.png
  GAN-based Art Generator using Deep learning/Model/GAN-based Art Generator using Deep learning (2).ipynb
  GAN-based Art Generator using Deep learning/Model/README.md
  GAN-based Art Generator using Deep learning/requirements.txt
Labels: Status: Approved, level 2, gssoc-ext

#965 Successfully Updated Code_of_conduct.md
  Code_of_conduct.md
Labels: Status: Approved, level 1, gssoc-ext

#971 Skin Disease Classification using Deep Learning Models
  Skin Disease Classification using Deep Learning Models/Dataset/README.md
  Skin Disease Classification using Deep Learning Models/Images/accuracy_plot.png
  Skin Disease Classification using Deep Learning Models/Images/class_distribution.png
  Skin Disease Classification using Deep Learning Models/Images/data_visualization.png
  Skin Disease Classification using Deep Learning Models/Images/loss_plot.png
  Skin Disease Classification using Deep Learning Models/Images/top2_accuracy_plot.png
  Skin Disease Classification using Deep Learning Models/Model/skin-disease-classification.ipynb
  Skin Disease Classification using Deep Learning Models/README.md
  Skin Disease Classification using Deep Learning Models/requirements.txt
Labels: Status: Approved, level 3, gssoc-ext

#980 AI Resume Analyzer #975
  AI Resume Analyzer/Resume Analyzer Sentence Transformers/README.md
  AI Resume Analyzer/Resume Analyzer Sentence Transformers/app.py
  AI Resume Analyzer/Resume Analyzer Sentence Transformers/requirements.txt
  AI Resume Analyzer/Resume Analyzer Sentence Transformers/results/382853996-ff312d66-7b70-4479-b1cf-06c9a871d853.png
  AI Resume Analyzer/Resume Analyzer Sentence Transformers/results/382854091-aed37f5f-361f-40e7-86a2-4ad77234db0d.png
  AI Resume Analyzer/Resume Analyzer Sentence Transformers/results/382854167-7ea6d358-40e3-4f57-908e-fd0a78d494b1.png
  AI Resume Analyzer/Resume Analyzer Sentence Transformers/resume_analyzer.py
  AI Resume Analyzer/Resume Analyzer Sentence Transformers/utils.py
  AI Resume Analyzer/Resume Analyzer With Gemini/Resume Application Tracking System(ATS)/README.md
  AI Resume Analyzer/Resume Analyzer With Gemini/Resume Application Tracking System(ATS)/app.py
  AI Resume Analyzer/Resume Analyzer With Gemini/Resume Application Tracking System(ATS)/output/ats percentage.pdf
  AI Resume Analyzer/Resume Analyzer With Gemini/Resume Application Tracking System(ATS)/output/ats.pdf
  AI Resume Analyzer/Resume Analyzer With Gemini/Resume Application Tracking System(ATS)/requirements.txt
  AI Resume Analyzer/Resume Analyzer With Gemini/ai_powered_resume_analyzer.py
  AI Resume Analyzer/Resume Analyzer With Gemini/readme.md
  AI Resume Analyzer/Resume Analyzer With Gemini/requirements.txt
  AI Resume Analyzer/Resume Analyzer With Gemini/result/resumeanalyzer.pdf
  AI Resume Analyzer/Resume Analyzer With Gemini/stramlit.py
Labels: Status: Approved, level 2, gssoc-ext

#983 Groundwater Arsenic Content Detection
  Groundwater Arsenic Content Detection/README.md
  Groundwater Arsenic Content Detection/data/Ground Water .csv
  Groundwater Arsenic Content Detection/images/Loss and accuracy.png
  Groundwater Arsenic Content Detection/images/RMSE Graph.png
  Groundwater Arsenic Content Detection/models/ann+woa.ipynb
  Groundwater Arsenic Content Detection/models/ann.ipynb
  Groundwater Arsenic Content Detection/models/random_forest.ipynb
Labels: Status: Approved, level 2, gssoc-ext

#987 Anomaly Detection in Time Series
  Anomaly Detection in Time Series /Dataset/Readme.md
  Anomaly Detection in Time Series /Image/Image 1.png
  Anomaly Detection in Time Series /Image/Image 2.png
  Anomaly Detection in Time Series /Image/Image 3.png
  Anomaly Detection in Time Series /Image/Image 4.png
  Anomaly Detection in Time Series /Image/Image 5.png
  Anomaly Detection in Time Series /Model/Anomaly Detection in Time Series.ipynb
  Anomaly Detection in Time Series /Model/README.md
  Anomaly Detection in Time Series /requirements.txt
Labels: Status: Approved, level 3, gssoc-ext

#978 Urban Sound Analysis - Sound Classification
  Urban Sound Classification using Deep Learning/Dataset/README.md
  Urban Sound Classification using Deep Learning/Dataset/TestPredUsingSpecImgCNN.csv
  Urban Sound Classification using Deep Learning/Dataset/TestPredUsingSpecImgResNet.csv
  Urban Sound Classification using Deep Learning/Dataset/TestPredUsingTimeSeriesNN.csv
  Urban Sound Classification using Deep Learning/Model/README.md
  Urban Sound Classification using Deep Learning/Model/Urban_Sound_Analysis_Sound_Classification.ipynb
  Urban Sound Classification using Deep Learning/requirement.txt
  Urban Sound Classification using Deep Learning/utils.py
Labels: Status: Approved, level 3, gssoc-ext
