Repository abhisheks008/DL-Simplified, pull requests merged in 2024-06, with the labels that each got.

#656 [Model and README Enhancement] Mushroom Classification using Deep Learning
  Mushroom Classification using Deep Learning/Images/CNN-Attention Accuracy.png
  Mushroom Classification using Deep Learning/Images/CNN-Attention Loss.png
  Mushroom Classification using Deep Learning/Images/Densenet121 Accuracy.png
  Mushroom Classification using Deep Learning/Images/Densenet121 Loss.png
  Mushroom Classification using Deep Learning/Images/Xception Accuracy.png
  Mushroom Classification using Deep Learning/Images/Xception Loss.png
  Mushroom Classification using Deep Learning/Model/Classification using Keras.ipynb
  Mushroom Classification using Deep Learning/README.md
  Mushroom Classification using Deep Learning/Readme.md
Labels: Status: Approved, level3, gssoc

#659 AI Vs Human Text Classification
  AI Vs Human Text Classification/Dataset/README.md
  AI Vs Human Text Classification/Images/ANN_Performance.png
  AI Vs Human Text Classification/Images/Data_Description.png
  AI Vs Human Text Classification/Images/Distribution_of_Human_AI-Generated_text.png
  AI Vs Human Text Classification/Images/LSTM_Performance.png
  AI Vs Human Text Classification/Images/Text_Length.png
  AI Vs Human Text Classification/Images/Word_Count.png
  AI Vs Human Text Classification/Images/word_cloud_ai.png
  AI Vs Human Text Classification/Images/word_cloud_human.png
  AI Vs Human Text Classification/Model/README.md
  AI Vs Human Text Classification/Model/ai-vs-human-text-classification.ipynb
  AI Vs Human Text Classification/requirements.txt
Labels: Status: Approved, Points Updated, level2, gssoc

#663 Sports Image Classification
  Sports Image Classification/Dataset/README.md
  Sports Image Classification/Images/EfficientNetB0_predictions/237b28b0-74e7-44cd-9190-a8e1c74583e6.png
  Sports Image Classification/Images/EfficientNetB0_predictions/600e20be-02c2-4e34-afc5-8255fe7ceb0e.png
  Sports Image Classification/Images/EfficientNetB0_predictions/e97f3a99-06ab-4091-a4cb-0c52e0f8e266.png
  Sports Image Classification/Images/EfficientNetB0_predictions/edd61747-0a67-4e44-8ac8-575db0ed883b.png
  Sports Image Classification/Images/EfficientNetB0_predictions/f0b4cc0c-bc35-4aef-b44b-9c83a2cf237c.png
  Sports Image Classification/Images/EfficientNetB0_predictions/f932a305-059d-46a9-aa04-6b6df6b8bbe9.png
  Sports Image Classification/Images/InceptionV3_predictions/014c8af8-227e-4d13-82e8-4d3c016c176a.png
  Sports Image Classification/Images/InceptionV3_predictions/3493d4e5-7b47-40fd-b884-b78a89dbe05b.png
  Sports Image Classification/Images/InceptionV3_predictions/8e9e4340-411d-46eb-9ad5-ab186f17b33b.png
  Sports Image Classification/Images/InceptionV3_predictions/a0278af7-ad0c-49e7-b5c2-c38424b016a6.png
  Sports Image Classification/Images/InceptionV3_predictions/d262930f-e7a6-47dd-afa1-6e79326090a2.png
  Sports Image Classification/Images/InceptionV3_predictions/dc89f4e9-3240-4dc6-be77-cb9cba0f2a9d.png
  Sports Image Classification/Images/MobieNetV2_predictions/2e6ecbbe-9f01-476d-af15-c578354d8260.png
  Sports Image Classification/Images/MobieNetV2_predictions/318512f5-a8d1-4e6b-bb4b-4aa52a7c5378.png
  Sports Image Classification/Images/MobieNetV2_predictions/3fdb3807-57fe-4b71-81d8-55dcc7b0fe9f.png
  Sports Image Classification/Images/MobieNetV2_predictions/63b4f459-bcba-47c0-ab6d-e046dca169da.png
  Sports Image Classification/Images/MobieNetV2_predictions/7d36752a-3c3b-4cbb-b5c1-6c662f4a8723.png
  Sports Image Classification/Images/MobieNetV2_predictions/accuracy.png
  Sports Image Classification/Images/MobieNetV2_predictions/ec836a26-e5f3-4e07-81ca-9cedb60bdee8.png
  Sports Image Classification/Images/Resnet50_predictions/322db5d3-7d52-4f54-8268-bea5d55feaf8.png
  Sports Image Classification/Images/Resnet50_predictions/3aa5211a-80d4-45f7-9f93-7fa4f32c1a71.png
  Sports Image Classification/Images/Resnet50_predictions/592f11ba-fb41-44e6-bd5e-b26f4ee3b34a.png
  Sports Image Classification/Images/Resnet50_predictions/62cf99c4-c8a4-4331-a4ad-607adc532d87.png
  Sports Image Classification/Images/Resnet50_predictions/653173c2-ef01-4fba-bb58-78e740dd71b5.png
  Sports Image Classification/Images/Resnet50_predictions/dbde1cae-6337-4236-af24-65f557592867.png
  Sports Image Classification/Images/Xception_predictions/162c7eb0-4671-4991-9f75-5345cc1854f6.png
  Sports Image Classification/Images/Xception_predictions/1e3161aa-d016-4e9a-900e-3cc5f11be2ee.png
  Sports Image Classification/Images/Xception_predictions/3f6d756f-917b-45a8-ba53-86a96b56bb2d.png
  Sports Image Classification/Images/Xception_predictions/49a7b8a8-b8f1-481d-9094-0edce1ac8932.png
  Sports Image Classification/Images/Xception_predictions/8132406e-b77e-4497-83a8-7b10d1aacd27.png
  Sports Image Classification/Images/Xception_predictions/Accuracy.png
  Sports Image Classification/Images/Xception_predictions/a6e78b79-83a2-4c28-bd2c-dcefbd858f97.png
  Sports Image Classification/Images/bar.png
  Sports Image Classification/Images/image_path_distribution.png
  Sports Image Classification/Images/pie-chart.png
  Sports Image Classification/Models/README.md
  Sports Image Classification/Models/models_SportsImageClassification_final.ipynb
  Sports Image Classification/requirement.txt
Labels: Status: Approved, level3, gssoc

#601 Covid Case Predictor
  Covid Case Predictor/Dataset/README.md
  Covid Case Predictor/Images/ARIMA.png
  Covid Case Predictor/Images/EDA1.png
  Covid Case Predictor/Images/EDA2.png
  Covid Case Predictor/Images/EDA3.png
  Covid Case Predictor/Images/EDA4.png
  Covid Case Predictor/Images/EDA5.png
  Covid Case Predictor/Images/EDA6.png
  Covid Case Predictor/Images/EDA7.png
  Covid Case Predictor/Images/EDA8.png
  Covid Case Predictor/Images/LSTM.png
  Covid Case Predictor/Images/SARIMAX.png
  Covid Case Predictor/Images/newplot.png
  Covid Case Predictor/Model/COVID_19_Tracker.ipynb
  Covid Case Predictor/README.md
  Covid Case Predictor/requirements.txt
Labels: Status: Approved, level2, gssoc

#668 Framing the Future
  Framing the Future/Dataset/README.md
  Framing the Future/Images/ANN_training_validation.png
  Framing the Future/Images/CNN_training_validation.png
  Framing the Future/Images/Result.jpeg
  Framing the Future/Images/accuracy_comparison_bar_with_values.png
  Framing the Future/Images/accuracy_plot.png
  Framing the Future/Images/avg_intensity_over_time.png
  Framing the Future/Images/datset.jpeg
  Framing the Future/Images/frame_intensity_distributions.png
  Framing the Future/Images/intensity_histogram.png
  Framing the Future/Images/loss_plot (1).png
  Framing the Future/Images/loss_plot.png
  Framing the Future/Images/mean_std_frames.png
  Framing the Future/Images/sequence_length_distribution.png
  Framing the Future/Model/Framing_the_Future_ann_cnn_lstm.ipynb
  Framing the Future/Model/README.md
  Framing the Future/requirements.txt
Labels: Status: Approved, Points Updated, level2, gssoc

#667 [Project Addition]: Breast Cancer Detection using DL - with Web App #554
  Breast Cancer Detection using DL with WebApp/Dataset/README.md
  Breast Cancer Detection using DL with WebApp/Images/Confusion Matrices.png
  Breast Cancer Detection using DL with WebApp/Images/Demo webpage.png
  Breast Cancer Detection using DL with WebApp/Images/MLP.png
  Breast Cancer Detection using DL with WebApp/Images/ResNet50.png
  Breast Cancer Detection using DL with WebApp/Images/VGG16.png
  Breast Cancer Detection using DL with WebApp/Model/Model.ipynb
  Breast Cancer Detection using DL with WebApp/Model/README.md
  Breast Cancer Detection using DL with WebApp/README.md
  Breast Cancer Detection using DL with WebApp/Webapp/README.md
  Breast Cancer Detection using DL with WebApp/Webapp/static/style.css
  Breast Cancer Detection using DL with WebApp/Webapp/templates/index.html
  Breast Cancer Detection using DL with WebApp/Webapp/webapp.py
  Breast Cancer Detection using DL with WebApp/requirements.txt
Labels: Status: Approved, Points Updated, level3, gssoc

#694 Emotion Classifier
  Emotion Classifier/Dataset/Emotion_classify_Data.csv
  Emotion Classifier/Dataset/README.md
  Emotion Classifier/Images/Average_Word_Length.png
  Emotion Classifier/Images/Character_Count_distribution.png
  Emotion Classifier/Images/Top20_Common_words.png
  Emotion Classifier/Images/Word_Count_distribution.png
  Emotion Classifier/Images/ann_model_accuracy_plot.png
  Emotion Classifier/Images/ann_model_loss_plot.png
  Emotion Classifier/Images/cnn_model_accuracy_plot.png
  Emotion Classifier/Images/cnn_model_loss_plot.png
  Emotion Classifier/Images/combined_emotion_distribution.png
  Emotion Classifier/Images/emotion_distribution.png
  Emotion Classifier/Images/model_comparison.png
  Emotion Classifier/Images/rnn_model_accuracy_plot.png
  Emotion Classifier/Images/rnn_model_loss_plot.png
  Emotion Classifier/Model/Emotion_Classifier_ann_cnn_rnn.ipynb
  Emotion Classifier/Model/README.md
  Emotion Classifier/requirements.txt
Labels: Status: Approved, level2, gssoc

#695 [Project Addition] Tomato-Leaf Classification using DL
  Tomato-Leaf Classification using DL/Dataset/README.md
  Tomato-Leaf Classification using DL/Images/CNN Accuracy.png
  Tomato-Leaf Classification using DL/Images/CNN Loss.png
  Tomato-Leaf Classification using DL/Images/DenseNet121 Accuracy.png
  Tomato-Leaf Classification using DL/Images/DenseNet121 Loss.png
  Tomato-Leaf Classification using DL/Images/EDA-1.png
  Tomato-Leaf Classification using DL/Images/EfficientNet Accuracy.png
  Tomato-Leaf Classification using DL/Images/EfficientNet Loss.png
  Tomato-Leaf Classification using DL/Images/Inception Accuracy.png
  Tomato-Leaf Classification using DL/Images/Inception Loss.png
  Tomato-Leaf Classification using DL/Images/RESNET50 Accuracy.png
  Tomato-Leaf Classification using DL/Images/RESNET50 Loss.png
  Tomato-Leaf Classification using DL/Images/VGG16 Accuracy.png
  Tomato-Leaf Classification using DL/Images/VGG16 loss.png
  Tomato-Leaf Classification using DL/Images/Xception Accuracy.png
  Tomato-Leaf Classification using DL/Images/Xception Loss.png
  Tomato-Leaf Classification using DL/Images/diseased leaf.png
  Tomato-Leaf Classification using DL/Images/eda.png
  Tomato-Leaf Classification using DL/Images/healthy leaf.png
  Tomato-Leaf Classification using DL/Model/tomato-leaf.ipynb
  Tomato-Leaf Classification using DL/README.md
Labels: Status: Approved, level3, gssoc

#699 [Project Addition] : Covid-19 X-Ray Image Classification
  COVID19-X Ray  Image Classification/Dataset/README.md
  COVID19-X Ray  Image Classification/Images/DenseNet121_predictions/0e775fe9-7a73-49cd-bf74-3fa33f76e2a5.png
  COVID19-X Ray  Image Classification/Images/DenseNet121_predictions/5ef690cb-9c3b-476b-8aeb-c63847941837.png
  COVID19-X Ray  Image Classification/Images/DenseNet121_predictions/7e024ac4-f3b4-4832-a776-0c2bb93b2c56.png
  COVID19-X Ray  Image Classification/Images/DenseNet121_predictions/8af20033-5829-4bdc-aeef-db9b5f63c387.png
  COVID19-X Ray  Image Classification/Images/InceptionV3_predictions/54a01ad5-ad98-4506-94a6-51cf178b3c4d.png
  COVID19-X Ray  Image Classification/Images/InceptionV3_predictions/55c53623-3f9b-4cf3-8624-7a509b7e7478.png
  COVID19-X Ray  Image Classification/Images/InceptionV3_predictions/8b73d11e-6df6-4332-9807-d0e37e2bb100.png
  COVID19-X Ray  Image Classification/Images/InceptionV3_predictions/9f819a75-9fca-4a51-99ac-097194a7d43e.png
  COVID19-X Ray  Image Classification/Images/MobieNetV2_predictions/4d8f7d2a-3ef1-4942-820b-3055bb4dc16f.png
  COVID19-X Ray  Image Classification/Images/MobieNetV2_predictions/6bbe9b43-1bc7-47e1-9aaa-69b4fa8ef1c6.png
  COVID19-X Ray  Image Classification/Images/MobieNetV2_predictions/92336470-2301-4a96-9a6e-fba21558bff6.png
  COVID19-X Ray  Image Classification/Images/MobieNetV2_predictions/feaf9857-f711-41b8-8086-343dc8610c46.png
  COVID19-X Ray  Image Classification/Images/VGG16_predictions/04701e86-c359-4103-899a-55faa0e6ea08.png
  COVID19-X Ray  Image Classification/Images/VGG16_predictions/4baaf1a6-0eed-4833-bf01-21628c39cf0e.png
  COVID19-X Ray  Image Classification/Images/VGG16_predictions/4e652e15-23c6-4317-861f-9bd5d14a5940.png
  COVID19-X Ray  Image Classification/Images/VGG16_predictions/af7f9523-cc21-454a-8f1c-35facfb2a89e.png
  COVID19-X Ray  Image Classification/Images/Xception_predictions/61a8aed3-bd82-4ff9-8ab9-5dd37a41d889.png
  COVID19-X Ray  Image Classification/Images/Xception_predictions/86bf04a4-43cc-4741-b300-8ad978c46132.png
  COVID19-X Ray  Image Classification/Images/Xception_predictions/89435ec5-a3b2-4942-a735-3ec28f9a918c.png
  COVID19-X Ray  Image Classification/Images/Xception_predictions/fb82b37b-d970-48cc-a159-8e9587f35f1a.png
  COVID19-X Ray  Image Classification/Images/bar_chart.png
  COVID19-X Ray  Image Classification/Images/image_path_distribution.png
  COVID19-X Ray  Image Classification/Images/pie.png
  COVID19-X Ray  Image Classification/Models/README.md
  COVID19-X Ray  Image Classification/Models/models_COVID_19.ipynb
  COVID19-X Ray  Image Classification/requirement.txt
Labels: Status: Approved, level3, gssoc

#557 [Project Addition]: Computed Tomography Analysis Using DL project
  Computed Tomography Analysis using DL/Dataset/README.md
  Computed Tomography Analysis using DL/Images/1st_model_architecture.png
  Computed Tomography Analysis using DL/Images/2nd-model_architecture.png
  Computed Tomography Analysis using DL/Images/3rd-model_architecture.png
  Computed Tomography Analysis using DL/Images/Image-Statistics-after-augmentation.png
  Computed Tomography Analysis using DL/Images/class-distribution.-After-Augmentation.png
  Computed Tomography Analysis using DL/Images/confusionMatrix-ResNet.png
  Computed Tomography Analysis using DL/Images/confusionMatrix-VGG16.png
  Computed Tomography Analysis using DL/Images/confusionMatrix-efficientNet.png
  Computed Tomography Analysis using DL/Images/output-Image-Statistics.png
  Computed Tomography Analysis using DL/Images/output-class-distribution.png
  Computed Tomography Analysis using DL/Images/output-sample-img-from-each-class.png
  Computed Tomography Analysis using DL/Images/train-val-cur-RESNet.png
  Computed Tomography Analysis using DL/Images/train-val-cur-VGG16png.png
  Computed Tomography Analysis using DL/Images/train-val-cur-efficientNet.png
  Computed Tomography Analysis using DL/Model/README.md
  Computed Tomography Analysis using DL/Model/dl_simplified_ct.ipynb
  Computed Tomography Analysis using DL/Model/requirments.txt
Labels: Status: Approved, level3, gssoc

#702 [Project Addition] AI Generated vs Real Images Classification using DL
  AI Generated vs Real Images Classification using DL/Dataset/README.md
  AI Generated vs Real Images Classification using DL/Images/1000_F_563719058_JXnzcPV4GRpWqmF5sqnqmbJ7ow3ca3DS.jpg
  AI Generated vs Real Images Classification using DL/Images/1WA1ZUTaiGV9YO5lVEPPFhA.png
  AI Generated vs Real Images Classification using DL/Images/85220_africa-21787_1920.rev.1600192341.jpg
  AI Generated vs Real Images Classification using DL/Images/CNN Accuracy.png
  AI Generated vs Real Images Classification using DL/Images/CNN Loss.png
  AI Generated vs Real Images Classification using DL/Images/DenseNet Accuracy.png
  AI Generated vs Real Images Classification using DL/Images/DenseNet Loss.png
  AI Generated vs Real Images Classification using DL/Images/Inception Accuracy.png
  AI Generated vs Real Images Classification using DL/Images/Inception Loss.png
  AI Generated vs Real Images Classification using DL/Images/Inception-Resnet-V2 Accuracy.png
  AI Generated vs Real Images Classification using DL/Images/Inception-Resnet-V2 Loss.png
  AI Generated vs Real Images Classification using DL/Images/VGG16 Accuracy.png
  AI Generated vs Real Images Classification using DL/Images/VGG16 Loss.png
  AI Generated vs Real Images Classification using DL/Images/Xception Accuracy.png
  AI Generated vs Real Images Classification using DL/Images/Xception Loss.png
  AI Generated vs Real Images Classification using DL/Images/beautiful-scenery-in-autumn-season-illustration-ai-generative-free-free-photo.jpg
  AI Generated vs Real Images Classification using DL/Model/ai_real_images.ipynb
  AI Generated vs Real Images Classification using DL/README.md
Labels: Status: Approved, level3, gssoc

#705 [Project Addition]: Thirty Musical Instruments Image Classification
  Musical Instruments Image Classification/Dataset/README.md
  Musical Instruments Image Classification/Images/DenseNet121/405a7263-2e26-4e0a-b6e0-d383d74acb08.png
  Musical Instruments Image Classification/Images/DenseNet121/48d6a85a-8274-4b0e-b327-65da5424b4b6.png
  Musical Instruments Image Classification/Images/DenseNet121/4b0bb137-90bd-4ffc-8c23-496c2c1eb088.png
  Musical Instruments Image Classification/Images/DenseNet121/8a11f5b7-4004-49b0-8a51-e552ddd91719.png
  Musical Instruments Image Classification/Images/InceptionV3_predictions/0715d283-e319-4c0c-9f93-5f2b7eb53ccc.png
  Musical Instruments Image Classification/Images/InceptionV3_predictions/9b31cde2-cb09-407f-87e7-4dc298027641.png
  Musical Instruments Image Classification/Images/InceptionV3_predictions/b7ad3e1a-70d2-4537-8a96-0b2ac5d8f8f8.png
  Musical Instruments Image Classification/Images/InceptionV3_predictions/e9b43bfd-9715-437d-ba47-89e0ba7f7011.png
  Musical Instruments Image Classification/Images/MobieNetV2_predictions/28ea1412-a0da-4f29-b523-223265ed705a.png
  Musical Instruments Image Classification/Images/MobieNetV2_predictions/9695b7e0-c79e-4ec9-b372-3a91ec298193.png
  Musical Instruments Image Classification/Images/MobieNetV2_predictions/b4174a2a-2a10-48dd-8469-fd9c5d4ec262.png
  Musical Instruments Image Classification/Images/MobieNetV2_predictions/c7cf489d-52e4-456c-99da-b8a14bce2d89.png
  Musical Instruments Image Classification/Images/Resnet50_predictions/0c0c4726-6f70-42c2-8156-2f5821018649.png
  Musical Instruments Image Classification/Images/Resnet50_predictions/47bf42e1-5b24-467c-9126-7f449f2ea3e0.png
  Musical Instruments Image Classification/Images/Resnet50_predictions/9dd5c405-dfb9-4be8-9eee-1a84d7fa249f.png
  Musical Instruments Image Classification/Images/Resnet50_predictions/a13e7cbc-72f0-40bc-83e2-891b6970bded.png
  Musical Instruments Image Classification/Images/Xception_predictions/46c54f60-7b66-4832-91bb-f61b5a7d9d35.png
  Musical Instruments Image Classification/Images/Xception_predictions/548cbfd4-cfc5-4624-a1fd-56940fe4de42.png
  Musical Instruments Image Classification/Images/Xception_predictions/710085b6-de7a-4d6d-a0a8-6aa8bfec79ee.png
  Musical Instruments Image Classification/Images/Xception_predictions/908b04ed-6901-4914-9a05-eb1e89b9bd3f.png
  Musical Instruments Image Classification/Images/bar.png
  Musical Instruments Image Classification/Images/path_distribution.png
  Musical Instruments Image Classification/Images/pie_chart.png
  Musical Instruments Image Classification/Models/README.md
  Musical Instruments Image Classification/Models/models_MusicInstrumentClassification.ipynb
  Musical Instruments Image Classification/requirement.txt
Labels: Status: Approved, level3, gssoc

#706 [Project Addition] Speech Sentiment Analysis using DL
  Speech Sentiment Analysis using DL/Dataset/README.md
  Speech Sentiment Analysis using DL/Images/DENSENET121 Accuracy.png
  Speech Sentiment Analysis using DL/Images/DENSENET121 Loss.png
  Speech Sentiment Analysis using DL/Images/EfficientNetB7 Accuracy.png
  Speech Sentiment Analysis using DL/Images/EfficientNetB7 Loss.png
  Speech Sentiment Analysis using DL/Images/InceptionV3 Accuracy.png
  Speech Sentiment Analysis using DL/Images/InceptionV3 Loss.png
  Speech Sentiment Analysis using DL/Images/Negative EDA.png
  Speech Sentiment Analysis using DL/Images/Neutral EDA.png
  Speech Sentiment Analysis using DL/Images/Positive EDA.png
  Speech Sentiment Analysis using DL/Images/RESNET50 Accuracy.png
  Speech Sentiment Analysis using DL/Images/RESNET50 Loss.png
  Speech Sentiment Analysis using DL/Images/VGG16 Accuracy.png
  Speech Sentiment Analysis using DL/Images/VGG16 Loss.png
  Speech Sentiment Analysis using DL/Images/Xception Accuracy.png
  Speech Sentiment Analysis using DL/Images/Xception Loss.png
  Speech Sentiment Analysis using DL/Model/speech-sentiment-analysis.ipynb
  Speech Sentiment Analysis using DL/README.md
Labels: Status: Approved, level3, gssoc

#708 Intrusion Detection
  Intrusion Detection/Dataset/README.md
  Intrusion Detection/Dataset/kddcup.data_10_percent.gz.zip
  Intrusion Detection/Images/ann_accuracy.png
  Intrusion Detection/Images/ann_loss.png
  Intrusion Detection/Images/attack_type.png
  Intrusion Detection/Images/cnn_accuracy.png
  Intrusion Detection/Images/cnn_loss.png
  Intrusion Detection/Images/correlation_heatmap.png
  Intrusion Detection/Images/deep_accuracy.png
  Intrusion Detection/Images/deep_loss.png
  Intrusion Detection/Images/flag.png
  Intrusion Detection/Images/logged_in.png
  Intrusion Detection/Images/model_comparison.png
  Intrusion Detection/Images/protocol_type.png
  Intrusion Detection/Images/service.png
  Intrusion Detection/Images/target.png
  Intrusion Detection/Model/Intrusion_Detection_ann_dnn_cnn.ipynb
  Intrusion Detection/Model/README.md
  Intrusion Detection/requirements.txt
Labels: Status: Approved, level2, gssoc

#717 [Project Addition] Turkey Almond Species Classification using DL
  Turkey Almond Species Classification using DL/Dataset/README.md
  Turkey Almond Species Classification using DL/Images/ALMOND.png
  Turkey Almond Species Classification using DL/Images/CNN Accuracy.png
  Turkey Almond Species Classification using DL/Images/CNN Loss.png
  Turkey Almond Species Classification using DL/Images/DENSENET121 Accuracy.png
  Turkey Almond Species Classification using DL/Images/DENSENET121 Loss.png
  Turkey Almond Species Classification using DL/Images/EDA.png
  Turkey Almond Species Classification using DL/Images/EfficientNetB7 Accuracy.png
  Turkey Almond Species Classification using DL/Images/EfficientNetB7 Loss.png
  Turkey Almond Species Classification using DL/Images/InceptionV3 Accuracy.png
  Turkey Almond Species Classification using DL/Images/InceptionV3 Loss.png
  Turkey Almond Species Classification using DL/Images/RESNET50 Accuracy.png
  Turkey Almond Species Classification using DL/Images/RESNET50 Loss.png
  Turkey Almond Species Classification using DL/Images/VGG16 Accuracy.png
  Turkey Almond Species Classification using DL/Images/VGG16 Loss.png
  Turkey Almond Species Classification using DL/Images/Xception Accuracy.png
  Turkey Almond Species Classification using DL/Images/Xception Loss.png
  Turkey Almond Species Classification using DL/Model/almond-classify.ipynb
  Turkey Almond Species Classification using DL/README.md
Labels: Status: Approved, level3, gssoc

#719 [Project Addition] : Natural Diamonds Image Classification
  Natural Diamonds Image Classification/Dataset/README.md
  Natural Diamonds Image Classification/Images/DenseNet121_predictions/11a9071b-c31d-454b-9128-8f125b3d2d3b.png
  Natural Diamonds Image Classification/Images/DenseNet121_predictions/7b2b72a2-6576-45f1-a217-8f8c5ee1b21a.png
  Natural Diamonds Image Classification/Images/DenseNet121_predictions/7fd4efc6-778c-4c0f-9f42-8ad0a466e22e.png
  Natural Diamonds Image Classification/Images/InceptionV3_predictions/55179ff7-4837-44f3-a81a-025523b5c7a8.png
  Natural Diamonds Image Classification/Images/InceptionV3_predictions/8e8399a2-0ffe-4b8d-a05e-c7f901d950a6.png
  Natural Diamonds Image Classification/Images/InceptionV3_predictions/d1011560-3542-43e3-936e-6611cd244546.png
  Natural Diamonds Image Classification/Images/MobieNetV2_predictions/1c6eb16a-ba0c-44bd-859f-dc93d04a512d.png
  Natural Diamonds Image Classification/Images/MobieNetV2_predictions/d9f67487-8192-404a-af02-19c4f7c3f49c.png
  Natural Diamonds Image Classification/Images/MobieNetV2_predictions/e4e2adc1-b1b2-4eaa-91b6-d722298cca6b.png
  Natural Diamonds Image Classification/Images/ResNet50_predictions/3ee68192-605b-4eb3-8960-f5cc9bdecc7c.png
  Natural Diamonds Image Classification/Images/ResNet50_predictions/78e8c330-dbe5-4854-af96-7b270eb6df7c.png
  Natural Diamonds Image Classification/Images/ResNet50_predictions/c3786613-ed4c-4c78-b4a9-83ac80816538.png
  Natural Diamonds Image Classification/Images/Xception_predictions/87e1b064-5b35-40b8-874a-2e553df38b8b.png
  Natural Diamonds Image Classification/Images/Xception_predictions/c17ae0c4-ead4-4dee-add5-9163685bf6e9.png
  Natural Diamonds Image Classification/Images/Xception_predictions/e02782bf-4641-4b2d-bb23-9a21db42d50b.png
  Natural Diamonds Image Classification/Images/bar.png
  Natural Diamonds Image Classification/Images/image_path.png
  Natural Diamonds Image Classification/Images/pie.png
  Natural Diamonds Image Classification/Models/README.md
  Natural Diamonds Image Classification/Models/models_NaturalDiamondShapePredictionipynb.ipynb
  Natural Diamonds Image Classification/requirement.txt
Labels: Status: Approved, level3, gssoc

#722 [Project Addition] : Indian Currency Detection using DL
  Indian Currency Detection using DL/Dataset/README.md
  Indian Currency Detection using DL/Images/DenseNet121/09ec2435-528f-467a-886c-5a6c563778c0.png
  Indian Currency Detection using DL/Images/DenseNet121/1aeba4fe-e49c-4f98-a78c-863e9105a6a8.png
  Indian Currency Detection using DL/Images/DenseNet121/43981767-5776-4649-bc6e-bee34ffac39c.png
  Indian Currency Detection using DL/Images/InceptionV3_predictions/32abcdf1-3a32-4a63-97ae-2500dee9bbb3.png
  Indian Currency Detection using DL/Images/InceptionV3_predictions/72d2062d-41f0-4455-9607-f437b4362a51.png
  Indian Currency Detection using DL/Images/InceptionV3_predictions/988c3a1f-cd99-4d61-b395-0b2617891bea.png
  Indian Currency Detection using DL/Images/NASNetMobile_predictions/28cea739-a49a-452d-8796-6d3069780991.png
  Indian Currency Detection using DL/Images/NASNetMobile_predictions/2e4cba78-0b17-4c85-9ee0-7bdd3522b9d1.png
  Indian Currency Detection using DL/Images/NASNetMobile_predictions/df1812d9-3e50-4de0-9024-af9d2f54d16e.png
  Indian Currency Detection using DL/Images/Resnet50V2_predictions/7cf8ba06-bb9e-4f23-9e39-c59923f3f300.png
  Indian Currency Detection using DL/Images/Resnet50V2_predictions/994bb09c-443a-4f94-a2b2-8457e0875228.png
  Indian Currency Detection using DL/Images/Resnet50V2_predictions/ce0ab66b-583d-4966-8848-bbe2032d5060.png
  Indian Currency Detection using DL/Images/Xception_predictions/1ee80672-8bf2-4946-a8c4-0c742949ae70.png
  Indian Currency Detection using DL/Images/Xception_predictions/5ddb2db6-6493-472e-9fb2-3510b6e214a2.png
  Indian Currency Detection using DL/Images/Xception_predictions/85aaddd6-dd79-42ad-b209-33f89cc5ff18.png
  Indian Currency Detection using DL/Images/bar.png
  Indian Currency Detection using DL/Images/image_path.png
  Indian Currency Detection using DL/Images/pie.png
  Indian Currency Detection using DL/Models/README.md
  Indian Currency Detection using DL/Models/models_IndianCurrencyDetection.ipynb
  Indian Currency Detection using DL/requirement.txt
Labels: Status: Approved, level3, gssoc

#724 [Project Addition] : Defective Captcha Image Recognition
  Defective Captcha Image Recognition/Dataset/README.md
  Defective Captcha Image Recognition/Images/DenseNet121/26b65009-f08a-4f95-988c-9cb4472d6262.png
  Defective Captcha Image Recognition/Images/DenseNet121/6a74efbb-237f-4ed1-9b1c-53a85ef79c29.png
  Defective Captcha Image Recognition/Images/DenseNet121/ead96295-c9ce-4363-978c-39a87363dca4.png
  Defective Captcha Image Recognition/Images/DenseNet121/fd5fbe70-f1f5-4d32-9f83-7af7b2b96dad.png
  Defective Captcha Image Recognition/Images/EfficientNetB1_predictions/110c0489-de74-4a4a-b156-2e3d0e5d1dcd.png
  Defective Captcha Image Recognition/Images/EfficientNetB1_predictions/351e8e1c-65d4-4459-bbdd-d25640feecd6.png
  Defective Captcha Image Recognition/Images/EfficientNetB1_predictions/57fabd9e-4a15-4f9b-84aa-f6fcdad06f2f.png
  Defective Captcha Image Recognition/Images/EfficientNetB1_predictions/db3e72d8-9787-49c5-ac29-0f883714fbe8-1.png
  Defective Captcha Image Recognition/Images/InceptionV3_predictions/0676b4cc-8572-4478-92e6-c18cf4287d9a.png
  Defective Captcha Image Recognition/Images/InceptionV3_predictions/4b389b70-a176-47d0-bdfd-0930742e88a0.png
  Defective Captcha Image Recognition/Images/InceptionV3_predictions/6ea5b05d-d870-48f7-a546-f4f6db373054.png
  Defective Captcha Image Recognition/Images/InceptionV3_predictions/d00c5e4d-f801-4e56-a7d4-741846506133.png
  Defective Captcha Image Recognition/Images/Resnet50V2_predictions/66ff8a40-eae3-4e85-8754-56c7d315e283.png
  Defective Captcha Image Recognition/Images/Resnet50V2_predictions/73526bcd-3bdb-479a-8d5a-eadf95e39bab.png
  Defective Captcha Image Recognition/Images/Resnet50V2_predictions/8e4ae9ac-48e0-47d6-82ae-1b6cf2513264.png
  Defective Captcha Image Recognition/Images/Resnet50V2_predictions/9dc0755b-8e5c-48fd-9f94-9aaebefa4fa6.png
  Defective Captcha Image Recognition/Images/Xception_predictions/10169ba4-59c7-4a8d-bc3b-6c874085b3f5.png
  Defective Captcha Image Recognition/Images/Xception_predictions/9897dbb4-b870-4efa-b927-8c966741cb1e.png
  Defective Captcha Image Recognition/Images/Xception_predictions/b849f400-11db-456e-bfae-d6eea992561d.png
  Defective Captcha Image Recognition/Images/Xception_predictions/f1bda14c-5c5d-40fa-a382-81ab3114a830.png
  Defective Captcha Image Recognition/Images/bar.png
  Defective Captcha Image Recognition/Images/image_path_distribution.png
  Defective Captcha Image Recognition/Images/pie.png
  Defective Captcha Image Recognition/Models/README.md
  Defective Captcha Image Recognition/Models/models_Defective_Captcha_Image_Recognition_.ipynb
  Defective Captcha Image Recognition/requirement.txt
Labels: Status: Approved, level3, gssoc

#728 [Project Addition] Indonesian Spice Classification using DL
  Indonesian Spice Classification using DL/Dataset/README.md
  Indonesian Spice Classification using DL/Images/CNN Accuracy.png
  Indonesian Spice Classification using DL/Images/CNN Loss.png
  Indonesian Spice Classification using DL/Images/DENSENET121 Accuracy.png
  Indonesian Spice Classification using DL/Images/DENSENET121 Loss.png
  Indonesian Spice Classification using DL/Images/EfficientNetB7 Accuracy.png
  Indonesian Spice Classification using DL/Images/EfficientNetB7 Loss.png
  Indonesian Spice Classification using DL/Images/Inception Accuracy.png
  Indonesian Spice Classification using DL/Images/Inception Loss.png
  Indonesian Spice Classification using DL/Images/RESNET50 Accuracy.png
  Indonesian Spice Classification using DL/Images/RESNET50 Loss.png
  Indonesian Spice Classification using DL/Images/VGG16 Accuracy.png
  Indonesian Spice Classification using DL/Images/VGG16 Loss.png
  Indonesian Spice Classification using DL/Images/Xception Accuracy.png
  Indonesian Spice Classification using DL/Images/Xception Loss.png
  Indonesian Spice Classification using DL/Images/biji ketumber.png
  Indonesian Spice Classification using DL/Images/duan jeruk.png
  Indonesian Spice Classification using DL/Images/jinten.png
  Indonesian Spice Classification using DL/Images/kayu secang.png
  Indonesian Spice Classification using DL/Model/indonesian-spices.ipynb
  Indonesian Spice Classification using DL/README.md
Labels: Status: Approved, level3, gssoc

#731 Airplane Passenger Prediction
  Airplane Passenger Prediction/Dataset/AirPassengers.csv
  Airplane Passenger Prediction/Dataset/README.md
  Airplane Passenger Prediction/Images/Autocorrelation.png
  Airplane Passenger Prediction/Images/Data.png
  Airplane Passenger Prediction/Images/Naiveforec.png
  Airplane Passenger Prediction/Images/SSA_forecast.png
  Airplane Passenger Prediction/Images/boxplot.png
  Airplane Passenger Prediction/Images/boxplot_monthly.png
  Airplane Passenger Prediction/Images/decomposed_plot.png
  Airplane Passenger Prediction/Images/expo.png
  Airplane Passenger Prediction/Images/histogram.png
  Airplane Passenger Prediction/Images/lstm_loss.png
  Airplane Passenger Prediction/Images/mape_comparison_with_values.png
  Airplane Passenger Prediction/Images/meanandsd.png
  Airplane Passenger Prediction/Images/prediction_plot_arima.png
  Airplane Passenger Prediction/Images/prophet.png
  Airplane Passenger Prediction/Model/AirplanePassenger_Forecasting.ipynb
  Airplane Passenger Prediction/Model/README.md
  Airplane Passenger Prediction/requirements.txt
Labels: Status: Approved, level3, gssoc

#736 [Project Addition] : Insect Detection and Classification using DL
  Insect Detection and Classification using DL/Dataset/README.md
  Insect Detection and Classification using DL/Images/DenseNet121/1cce4d35-a9e2-49e6-bec1-8f540ef6c640.png
  Insect Detection and Classification using DL/Images/DenseNet121/aedd4d8a-e516-42a4-b16b-1a063173efaa.png
  Insect Detection and Classification using DL/Images/DenseNet121/e0e74036-b174-421c-9222-757ca1059eb7.png
  Insect Detection and Classification using DL/Images/DenseNet121/ef9173f3-63b2-4119-ad96-81a93c4c1aac.png
  Insect Detection and Classification using DL/Images/InceptionV3_predictions/28c05d19-f793-4a18-859a-13e8e68756b5.png
  Insect Detection and Classification using DL/Images/InceptionV3_predictions/3df0fda8-f842-4a34-91c5-4687e1112e14.png
  Insect Detection and Classification using DL/Images/InceptionV3_predictions/68e783d1-408d-4314-8b3c-a9c1439a6494.png
  Insect Detection and Classification using DL/Images/InceptionV3_predictions/8a4134d7-8ad2-4eac-a738-b3453efded17.png
  Insect Detection and Classification using DL/Images/ResNet101V2_predictions/1a2bbd11-337c-4763-b853-9c34877eaab3.png
  Insect Detection and Classification using DL/Images/ResNet101V2_predictions/776d63f5-4fd0-41fc-bfd2-90ea5872f76b.png
  Insect Detection and Classification using DL/Images/ResNet101V2_predictions/9b8bd6b4-b5cb-4c8c-ad12-29aca4d74d00.png
  Insect Detection and Classification using DL/Images/ResNet101V2_predictions/ead5d95c-7b1f-4e59-a9c6-f28e56c574c0.png
  Insect Detection and Classification using DL/Images/Resnet50V2_predictions/3ea9611d-9697-460b-bfaf-4c418cee524c.png
  Insect Detection and Classification using DL/Images/Resnet50V2_predictions/7098ef1d-a285-437a-a23a-d4cf99d385a9.png
  Insect Detection and Classification using DL/Images/Resnet50V2_predictions/8f659648-c411-4792-a3fc-3a3116a9ab57.png
  Insect Detection and Classification using DL/Images/Resnet50V2_predictions/b3f8ba55-849c-47b6-b705-59fe79005f17.png
  Insect Detection and Classification using DL/Images/Xception_predictions/35d1cedc-35ce-4b22-8902-0e910812e0f0.png
  Insect Detection and Classification using DL/Images/Xception_predictions/4cf60ed1-2d77-47f6-92b0-36d8aa288246.png
  Insect Detection and Classification using DL/Images/Xception_predictions/630a36ad-e213-4bff-b3bd-196f8735c95e.png
  Insect Detection and Classification using DL/Images/Xception_predictions/c4c6adf8-d347-4a62-9ec1-6b1163dcaf02.png
  Insect Detection and Classification using DL/Images/bar.png
  Insect Detection and Classification using DL/Images/image_path_distribution.png
  Insect Detection and Classification using DL/Images/pie_chart.png
  Insect Detection and Classification using DL/Models/README.md
  Insect Detection and Classification using DL/Models/models_Insect_Detection_and_Classification.ipynb
  Insect Detection and Classification using DL/requirement.txt
Labels: Status: Approved, level3, gssoc

#735 Thyroid Cancer Recurrence Prediction
  Thyroid Cancer Recurrence Prediction/Dataset/README.md
  Thyroid Cancer Recurrence Prediction/Dataset/Thyroid_Disease_Data.csv
  Thyroid Cancer Recurrence Prediction/Dataset/final_data.csv
  Thyroid Cancer Recurrence Prediction/Dataset/final_test.csv
  Thyroid Cancer Recurrence Prediction/Dataset/final_train.csv
  Thyroid Cancer Recurrence Prediction/Images/Adenopathy_Distribution.png
  Thyroid Cancer Recurrence Prediction/Images/Age_Distribution.png
  Thyroid Cancer Recurrence Prediction/Images/Age_Distribution_by_Smoking_Status.png
  Thyroid Cancer Recurrence Prediction/Images/Correlation_Matrix.png
  Thyroid Cancer Recurrence Prediction/Images/Gender_Distribution.png
  Thyroid Cancer Recurrence Prediction/Images/MLP_Model_Accuracy.png
  Thyroid Cancer Recurrence Prediction/Images/MLP_model_accuracy.png
  Thyroid Cancer Recurrence Prediction/Images/MosaicPlot.png
  Thyroid Cancer Recurrence Prediction/Images/Thyroid_Cancer_Recurrence_Dataset_EDA.png
  Thyroid Cancer Recurrence Prediction/Model/Profile_Report.html
  Thyroid Cancer Recurrence Prediction/Model/Thyroid_Cancer_Recurrence_Dataset_EDA.ipynb
  Thyroid Cancer Recurrence Prediction/Model/Thyroid_Cancer_Recurrence_Prediction_w_DL.ipynb
  Thyroid Cancer Recurrence Prediction/Model/autogluon_model.ipynb
  Thyroid Cancer Recurrence Prediction/Model/autogluon_model.pkl
  Thyroid Cancer Recurrence Prediction/Model/mlp_model.h5
  Thyroid Cancer Recurrence Prediction/Model/mlp_model.ipynb
  Thyroid Cancer Recurrence Prediction/Model/tabnet_model.ipynb
  Thyroid Cancer Recurrence Prediction/Model/tabnet_model.pt
  Thyroid Cancer Recurrence Prediction/Model/tabnet_model_params.json
  Thyroid Cancer Recurrence Prediction/README.md
  Thyroid Cancer Recurrence Prediction/requirements.txt
Labels: Status: Approved, level3, gssoc

#741 [Project Addition] Arabic Date Species Classification using DL
  Arabic Dates Classification using DL/Dataset/README.md
  Arabic Dates Classification using DL/Images/CNN Accuracy.png
  Arabic Dates Classification using DL/Images/CNN Loss.png
  Arabic Dates Classification using DL/Images/DenseNet121 Accuracy.png
  Arabic Dates Classification using DL/Images/DenseNet121 Loss.png
  Arabic Dates Classification using DL/Images/EDA.png
  Arabic Dates Classification using DL/Images/EfficientNetB7 Accuracy.png
  Arabic Dates Classification using DL/Images/EfficientNetB7 Loss.png
  Arabic Dates Classification using DL/Images/InceptionV3 Accuracy.png
  Arabic Dates Classification using DL/Images/InceptionV3 Loss.png
  Arabic Dates Classification using DL/Images/RESNET50 Accuracy.png
  Arabic Dates Classification using DL/Images/RESNET50 Loss.png
  Arabic Dates Classification using DL/Images/VGG16 Accuracy.png
  Arabic Dates Classification using DL/Images/VGG16 Loss.png
  Arabic Dates Classification using DL/Images/Xception Accuracy.png
  Arabic Dates Classification using DL/Images/Xception Loss.png
  Arabic Dates Classification using DL/Images/display.png
  Arabic Dates Classification using DL/Images/pie distribution.png
  Arabic Dates Classification using DL/Model/dates-classify.ipynb
  Arabic Dates Classification using DL/README.md
Labels: Status: Approved, level3, gssoc

#743 [Project Addition] Eye Disease Classification using DL
  Eye Disease Classification using DL/Dataset/README.md
  Eye Disease Classification using DL/Images/CNN Accuracy.png
  Eye Disease Classification using DL/Images/CNN Loss.png
  Eye Disease Classification using DL/Images/Cataract.png
  Eye Disease Classification using DL/Images/DENSENET121 Accuracy.png
  Eye Disease Classification using DL/Images/DENSENET121 Loss.png
  Eye Disease Classification using DL/Images/Diabetic Retinopathy.png
  Eye Disease Classification using DL/Images/EDA.png
  Eye Disease Classification using DL/Images/Glaucoma.png
  Eye Disease Classification using DL/Images/InceptionV3 Accuracy.png
  Eye Disease Classification using DL/Images/InceptionV3 Loss.png
  Eye Disease Classification using DL/Images/MobileNet Accuracy.png
  Eye Disease Classification using DL/Images/MobileNet Loss.png
  Eye Disease Classification using DL/Images/Normal.png
  Eye Disease Classification using DL/Images/RESNET50 Accuracy.png
  Eye Disease Classification using DL/Images/RESNET50 Loss.png
  Eye Disease Classification using DL/Images/VGG16 Accuracy.png
  Eye Disease Classification using DL/Images/VGG16 Loss.png
  Eye Disease Classification using DL/Images/Xception Accuracy.png
  Eye Disease Classification using DL/Images/Xception Loss.png
  Eye Disease Classification using DL/Model/eye-disease-classify.ipynb
  Eye Disease Classification using DL/README.md
Labels: Status: Approved, level3, gssoc

#746 [Project Addition] : Pharmaceutical Drugs and Vitamins Images Detection
  Pharmaceutical Drugs and Vitamins Images Detection/Dataset/README.md
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/87918c94-5dc8-410e-94f0-fd1f8d08ebff.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/992a7274-9ea6-4757-ad0a-7c4e41805fae.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/dfb74364-4379-4131-ae23-73e3c5e80d06.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/DenseNet121/f508171e-a64c-4b62-b1ed-9ce1fddb74c6.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/02509165-66d3-4164-8f0d-1c6a8b57536a.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/385088f1-0165-4ede-a392-c686b0904e29.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/856f6215-1ccf-421a-be41-bdc7817b1590.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/InceptionV3_predictions/dd0bc14e-65d1-4726-979e-e89d2386a6eb.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/18b4bf42-2e21-4cd3-afc3-e7c672422e6e.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/20fd282c-2edc-48ce-8a52-c7d87a5089cb.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/982a84ee-788a-4bb2-89d5-4304a8a56eac.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/MobileNet_predictions/c35dcb78-6440-4864-98a6-3a2ea4cebb1b.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/13e67132-466a-472b-877e-0ed951a2809e.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/2d50be9e-1915-43a9-87ec-486c5d8c8ef5.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/3581db0f-bd7f-46d5-a93e-d47baced07bd.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Resnet50V2_predictions/eb57435f-2201-4f0b-98da-b790e13750a6.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/1c85d549-30b2-4d7d-b720-85eb84ab1644.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/773ea5a9-7573-4057-968e-4fa8926af4cb.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/976ab080-7145-4f37-aa6a-73713f8a6a9e.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/Xception_predictions/ed06fe5c-e8a8-42d4-8d38-11da2ac72202.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/bar.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/image_path_distribution.png
  Pharmaceutical Drugs and Vitamins Images Detection/Images/pie_chart.png
  Pharmaceutical Drugs and Vitamins Images Detection/Models/README.md
  Pharmaceutical Drugs and Vitamins Images Detection/Models/models_Pharmaceutical_Drugs_and_Vitamins_Images_Detection_(1).ipynb
  Pharmaceutical Drugs and Vitamins Images Detection/requirement.txt
Labels: Status: Approved, level3, gssoc

#748 [Project Addition] : Wild Animal Image Classification
  Wild Animal Image Classification/Dataset/README.md
  Wild Animal Image Classification/Images/DenseNet121/56103b40-5077-4054-bb55-51f1e20763c4.png
  Wild Animal Image Classification/Images/DenseNet121/8669099f-0c8f-44fc-90e0-6de2a77aa054.png
  Wild Animal Image Classification/Images/DenseNet121/ace4ba51-00c2-4744-9624-725601d95f43.png
  Wild Animal Image Classification/Images/DenseNet121/dbe2b5af-fbfd-47ba-b969-b7eb0d73edf5.png
  Wild Animal Image Classification/Images/DenseNet169_predictions/39be4709-81c1-4e47-a160-e826084b3565.png
  Wild Animal Image Classification/Images/DenseNet169_predictions/49094e58-a086-48f2-82c3-d3369adc8fdc.png
  Wild Animal Image Classification/Images/DenseNet169_predictions/818ee25a-af56-4dc5-b2d6-a39786e8335c.png
  Wild Animal Image Classification/Images/DenseNet169_predictions/a7731182-5c50-4e63-b1bf-000a71086768.png
  Wild Animal Image Classification/Images/InceptionV3_predictions/0164b9bf-bd42-4d79-ba7e-0260a2a3eb0c.png
  Wild Animal Image Classification/Images/InceptionV3_predictions/4a7026fa-0867-4596-805c-08f93bfb02f1.png
  Wild Animal Image Classification/Images/InceptionV3_predictions/66a827a9-fac6-4633-a815-d01ad8f36718.png
  Wild Animal Image Classification/Images/InceptionV3_predictions/90b2d288-e6e1-4b2b-bebc-9c70eb67dab4.png
  Wild Animal Image Classification/Images/Resnet50V2_predictions/288b503e-ad83-4756-9f84-345513c03188.png
  Wild Animal Image Classification/Images/Resnet50V2_predictions/695db48c-a679-45e1-b856-e9e9bdf61e95.png
  Wild Animal Image Classification/Images/Resnet50V2_predictions/838d663e-91d8-4a4c-9746-5c79a4dc9d35.png
  Wild Animal Image Classification/Images/Resnet50V2_predictions/bf7eaef2-7a16-4dba-9d7b-c7861ac1e154.png
  Wild Animal Image Classification/Images/Xception_predictions/2452c871-86ea-4f08-9f4e-1bb3e41cfb3d.png
  Wild Animal Image Classification/Images/Xception_predictions/41921a4a-2f65-4dd0-8634-f52ffaffb6de.png
  Wild Animal Image Classification/Images/Xception_predictions/568e7211-0eaa-4ba5-a872-dde8cb534372.png
  Wild Animal Image Classification/Images/Xception_predictions/d3cd5bf1-38cd-43ab-88fe-4251288fe88d.png
  Wild Animal Image Classification/Images/bar.png
  Wild Animal Image Classification/Images/image_path_distribution.png
  Wild Animal Image Classification/Images/pie.png
  Wild Animal Image Classification/Models/README.md
  Wild Animal Image Classification/Models/models_Wild_animal_Image_classification.ipynb
  Wild Animal Image Classification/requirement.txt
Labels: Status: Approved, level3, gssoc

#749 [Project Addition] Cataract Detection using DL
  Cataract Detection using DL/Dataset/README.md
  Cataract Detection using DL/Images/CNN Accuracy.png
  Cataract Detection using DL/Images/CNN Loss.png
  Cataract Detection using DL/Images/Cataract.png
  Cataract Detection using DL/Images/DenseNet121 Accuracy.png
  Cataract Detection using DL/Images/DenseNet121 Loss.png
  Cataract Detection using DL/Images/EDA.png
  Cataract Detection using DL/Images/InceptionV3 Accuracy.png
  Cataract Detection using DL/Images/InceptionV3 Loss.png
  Cataract Detection using DL/Images/MobileNet Accuracy.png
  Cataract Detection using DL/Images/MobileNet Loss.png
  Cataract Detection using DL/Images/Normal.png
  Cataract Detection using DL/Images/RESNET50 Accuracy.png
  Cataract Detection using DL/Images/RESNET50 Loss.png
  Cataract Detection using DL/Images/VGG16 Accuracy.png
  Cataract Detection using DL/Images/VGG16 Loss.png
  Cataract Detection using DL/Images/Xception Accuracy.png
  Cataract Detection using DL/Images/Xception Loss.png
  Cataract Detection using DL/Model/cataract-detect.ipynb
  Cataract Detection using DL/README.md
Labels: Status: Approved, level3, gssoc

#750 [Project Addition] : Fake and Real Face Detection using DL
  Fake and Real Face Detection using DL/Dataset/README.md
  Fake and Real Face Detection using DL/Images/DenseNet121/46ff97c0-cad9-4916-ba31-565f7ff2ae0e.png
  Fake and Real Face Detection using DL/Images/DenseNet121/98cc9ef2-237f-4c40-953e-ecd31c0f4a2c.png
  Fake and Real Face Detection using DL/Images/DenseNet121/c242d566-fcc2-4ba7-ac0a-c860991d23e7.png
  Fake and Real Face Detection using DL/Images/DenseNet121/ef81aca5-1b84-4144-8e32-1fbe009cbfe9.png
  Fake and Real Face Detection using DL/Images/DenseNet169_predictions/558d4761-1128-48d5-a7ea-db7be6523d6e.png
  Fake and Real Face Detection using DL/Images/DenseNet169_predictions/967037c6-cb62-4580-a16c-e29a3267000f.png
  Fake and Real Face Detection using DL/Images/DenseNet169_predictions/dfbb22ef-7ddd-4549-8ab6-17c330160711.png
  Fake and Real Face Detection using DL/Images/DenseNet169_predictions/fa526a44-08d3-4909-998f-03f2f70cf82b.png
  Fake and Real Face Detection using DL/Images/InceptionV3_predictions/588c82f0-dd69-403b-b821-56e9ddd52b0b.png
  Fake and Real Face Detection using DL/Images/InceptionV3_predictions/82f201cf-1b42-4746-9972-cadd52694cbd.png
  Fake and Real Face Detection using DL/Images/InceptionV3_predictions/d377c3b7-db8d-4ae9-8599-38e8f995c022.png
  Fake and Real Face Detection using DL/Images/InceptionV3_predictions/fdb31897-a278-4d40-ba96-19d3fe817c00.png
  Fake and Real Face Detection using DL/Images/Resnet50V2_predictions/121d3148-317f-4790-be95-5ae133948f75.png
  Fake and Real Face Detection using DL/Images/Resnet50V2_predictions/28c4d1c4-c37c-4468-ae6f-af44fc5ef0e1.png
  Fake and Real Face Detection using DL/Images/Resnet50V2_predictions/49ff56f9-48b5-4a9d-9649-262b69f43ec9.png
  Fake and Real Face Detection using DL/Images/Resnet50V2_predictions/a5fb6340-bf31-46c2-8022-2d6bce1ebabe.png
  Fake and Real Face Detection using DL/Images/Xception_predictions/613de73b-43d0-4fde-91d4-6d618db7a7b5.png
  Fake and Real Face Detection using DL/Images/Xception_predictions/bfcf4aa0-1697-4043-881d-4555b4ec6477.png
  Fake and Real Face Detection using DL/Images/Xception_predictions/c7076c59-4507-4da1-967a-14c4b104a2d6.png
  Fake and Real Face Detection using DL/Images/Xception_predictions/f34c78bb-57d9-40c8-a851-0639ee25fdf1.png
  Fake and Real Face Detection using DL/Images/bar.png
  Fake and Real Face Detection using DL/Images/image_path.png
  Fake and Real Face Detection using DL/Images/pie.png
  Fake and Real Face Detection using DL/Models/README.md
  Fake and Real Face Detection using DL/Models/models_Fake_Vs_Real_Face_Detection.ipynb
  Fake and Real Face Detection using DL/requirement.txt
Labels: Status: Approved, level3, gssoc

#753 [Project Addition] Fracture Detection using DL
  Fracture Detection using DL/Dataset/README.md
  Fracture Detection using DL/Images/CNN Accuracy.png
  Fracture Detection using DL/Images/CNN Loss.png
  Fracture Detection using DL/Images/DenseNet121 Accuracy.png
  Fracture Detection using DL/Images/DenseNet121 Loss.png
  Fracture Detection using DL/Images/EDA.png
  Fracture Detection using DL/Images/Fracture.png
  Fracture Detection using DL/Images/InceptionV3 Accuracy.png
  Fracture Detection using DL/Images/InceptionV3 Loss.png
  Fracture Detection using DL/Images/MobileNet Accuracy.png
  Fracture Detection using DL/Images/MobileNet Loss.png
  Fracture Detection using DL/Images/Not fractured.png
  Fracture Detection using DL/Images/RESNET50 Accuracy.png
  Fracture Detection using DL/Images/RESNET50 Loss.png
  Fracture Detection using DL/Images/VGG16 Accuracy.png
  Fracture Detection using DL/Images/VGG16 Loss.png
  Fracture Detection using DL/Images/Xception Accuracy.png
  Fracture Detection using DL/Images/Xception Loss.png
  Fracture Detection using DL/Model/fracture-classify.ipynb
  Fracture Detection using DL/README.md
Labels: Status: Approved, level3, gssoc

#758 [Project Addition]: Almond Varieties Image Classification
  Almond Varieties Image Classification/Dataset/README.md
  Almond Varieties Image Classification/Images/EDA_1.png
  Almond Varieties Image Classification/Images/EDA_2.png
  Almond Varieties Image Classification/Images/InceptionV3_results.png
  Almond Varieties Image Classification/Images/ResNet_results.png
  Almond Varieties Image Classification/Images/VGG19_results.png
  Almond Varieties Image Classification/Models/Almonds_Varieties_InceptionV3.ipynb
  Almond Varieties Image Classification/Models/Almonds_Varieties_ResNet50.ipynb
  Almond Varieties Image Classification/Models/Almonds_Varieties_VGG19.ipynb
  Almond Varieties Image Classification/Models/README.md
  Almond Varieties Image Classification/README.md
Labels: Status: Approved, level2, gssoc

#677 Real or Fake Job Posting Prediction
  Real or Fake Job Posting Prediction/Dataset/README.md
  Real or Fake Job Posting Prediction/Images/ANN.png
  Real or Fake Job Posting Prediction/Images/BiLSTM.png
  Real or Fake Job Posting Prediction/Images/BiLSTM_cm.png
  Real or Fake Job Posting Prediction/Images/CNN.png
  Real or Fake Job Posting Prediction/Images/CNN_cm.png
  Real or Fake Job Posting Prediction/Images/Distribution_of_employment_type.png
  Real or Fake Job Posting Prediction/Images/Distribution_of_fraudulent_job_posting.png
  Real or Fake Job Posting Prediction/Images/Distribution_of_function.png
  Real or Fake Job Posting Prediction/Images/Distribution_of_has_company_logo.png
  Real or Fake Job Posting Prediction/Images/Distribution_of_has_questions.png
  Real or Fake Job Posting Prediction/Images/Distribution_of_required_education.png
  Real or Fake Job Posting Prediction/Images/Distribution_of_required_experience.png
  Real or Fake Job Posting Prediction/Images/Distribution_of_telecommunicating.png
  Real or Fake Job Posting Prediction/Images/LSTM.png
  Real or Fake Job Posting Prediction/Images/ann_cm.png
  Real or Fake Job Posting Prediction/Images/lstm_cm.png
  Real or Fake Job Posting Prediction/Images/word_cloud_fake.png
  Real or Fake Job Posting Prediction/Images/word_cloud_real.png
  Real or Fake Job Posting Prediction/Model/README.md
  Real or Fake Job Posting Prediction/Model/real-fake-job-posting-prediction.ipynb
  Real or Fake Job Posting Prediction/requirements.txt
Labels: Status: Approved, level3, gssoc

#766 [Project Addition] Pomegranate Disease Classification using DL
  Pomegranate Disease Classification using DL/Dataset/README.md
  Pomegranate Disease Classification using DL/Images/Alternaria.jpg
  Pomegranate Disease Classification using DL/Images/Anthracnose.png
  Pomegranate Disease Classification using DL/Images/Bacterial Blight.png
  Pomegranate Disease Classification using DL/Images/CNN Accuracy.png
  Pomegranate Disease Classification using DL/Images/CNN Loss.png
  Pomegranate Disease Classification using DL/Images/Cercospora.png
  Pomegranate Disease Classification using DL/Images/DENSENET121 Accuracy.png
  Pomegranate Disease Classification using DL/Images/DENSENET121 Loss.png
  Pomegranate Disease Classification using DL/Images/EDA.png
  Pomegranate Disease Classification using DL/Images/Healthy.png
  Pomegranate Disease Classification using DL/Images/InceptionV3 Accuracy.png
  Pomegranate Disease Classification using DL/Images/InceptionV3 Loss.png
  Pomegranate Disease Classification using DL/Images/MobileNet Accuracy.png
  Pomegranate Disease Classification using DL/Images/MobileNet Loss.png
  Pomegranate Disease Classification using DL/Images/RESNET50 Accuracy.png
  Pomegranate Disease Classification using DL/Images/RESNET50 Loss.png
  Pomegranate Disease Classification using DL/Images/VGG16 Accuracy.png
  Pomegranate Disease Classification using DL/Images/VGG16 Loss.png
  Pomegranate Disease Classification using DL/Images/Xception Accuracy.png
  Pomegranate Disease Classification using DL/Images/Xception Loss.png
  Pomegranate Disease Classification using DL/Model/pomegranate-disease.ipynb
  Pomegranate Disease Classification using DL/README.md
  Pomegranate Disease Classification using DL/requirements.txt
Labels: Status: Approved, level3, gssoc

#769 [Project Addition] : Chest X-ray - Tuberculosis Disease Prediction
  Chest X-ray - Tuberculosis Disease Prediction/Dataset/README.md
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/07d23d26-602e-45b3-89a9-adc19a24a93b.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/73a27086-f976-43d2-bbc3-34d1148e2cdd.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/83be1e95-d591-41cb-b6a5-330af1de15c1.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/DenseNet121/941fe4f5-8176-4fc0-b2e5-1cc41e58138f.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/01209f9f-e709-4a7a-a14b-97f98cdb16a6.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/a970945f-aedf-4ac7-a4ee-e3f01fedcbb4.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/b12522d2-e7f9-43bb-b9ec-0d862dfb3a2b.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/InceptionV3_predictions/b6627c83-2b71-411e-8a3b-ecb8a93b35f9.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/495e63b4-00da-42c1-9f88-21f74bcd083a.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/79b66dc3-b8f7-42fb-b782-4764d3bcbf54.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/cd214e19-6e33-4a6d-9d40-51a6fc182425.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/MobileNetV2_predictions/cef531b0-8c62-474d-8432-3b28d31586dd.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/09672514-0d74-4ba3-b83f-34b7dce90ce6.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/66b55d5b-c0dc-4c22-9c9d-574ad61aab1e.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/7df6144a-37f3-47d5-b42b-39a6d0e83ff4.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Resnet50V2_predictions/c9365032-e058-4e78-93f9-e9654992bbf1.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/369f577f-fde9-48eb-a4ad-d9ee64a8f903.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/3c63b249-af3e-4732-8109-7595c30b09ec.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/bef2f489-15d6-4f72-a33e-5c306d33833f.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/Xception_predictions/cd93c4f3-2055-4daf-919a-9d88bf1d18ca.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/bar_chart.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/image_path_distribution.png
  Chest X-ray - Tuberculosis Disease Prediction/Images/pie_chart.png
  Chest X-ray - Tuberculosis Disease Prediction/Models/README.md
  Chest X-ray - Tuberculosis Disease Prediction/Models/models_Chest_X_ray_Tuberculosis_Disease_Prediction(1).ipynb
  Chest X-ray - Tuberculosis Disease Prediction/requirement.txt
Labels: Status: Approved, level3, gssoc

#770 Simple object Detection
  Simple Object Detection/Dataset/README.md
  Simple Object Detection/Dataset/archive.zip
  Simple Object Detection/Images/ANN_loss.png
  Simple Object Detection/Images/ANN_mae.png
  Simple Object Detection/Images/CNN_loss.png
  Simple Object Detection/Images/CNN_mae.png
  Simple Object Detection/Images/DNN_loss.png
  Simple Object Detection/Images/DNN_mae.png
  Simple Object Detection/Images/Distribution.png
  Simple Object Detection/Images/LSTM_loss.png
  Simple Object Detection/Images/LSTM_mae.png
  Simple Object Detection/Images/RNN_loss.png
  Simple Object Detection/Images/RNN_mae.png
  Simple Object Detection/Images/box-size-didtribution.png
  Simple Object Detection/Images/comparison_bar_graph_val_loss.png
  Simple Object Detection/Images/comparison_bar_graph_val_mae.png
  Simple Object Detection/Images/histogram-xmax.png
  Simple Object Detection/Images/histogram-xmin.png
  Simple Object Detection/Images/histogram-ymax.png
  Simple Object Detection/Images/histogram-ymin.png
  Simple Object Detection/Images/plot.png
  Simple Object Detection/Images/size-location.png
  Simple Object Detection/Model/README.md
  Simple Object Detection/Model/Simple_object_detection_ann_cnn_dnn_lstm_rnn.ipynb
  Simple Object Detection/requirements.txt
Labels: Status: Approved, level3, gssoc

#773 [Project Addition] Cotton Disease Classification using DL
  Cotton Disease Classification using DL/Dataset/README.md
  Cotton Disease Classification using DL/Images/Aphids.png
  Cotton Disease Classification using DL/Images/Army Worms.png
  Cotton Disease Classification using DL/Images/Bacterial Blight.png
  Cotton Disease Classification using DL/Images/CNN Accuracy.png
  Cotton Disease Classification using DL/Images/CNN Loss.png
  Cotton Disease Classification using DL/Images/DenseNet-121 Accuracy.png
  Cotton Disease Classification using DL/Images/DenseNet-121 Loss.png
  Cotton Disease Classification using DL/Images/EDA.png
  Cotton Disease Classification using DL/Images/Healthy.png
  Cotton Disease Classification using DL/Images/InceptionV3 Accuracy.png
  Cotton Disease Classification using DL/Images/InceptionV3 Loss.png
  Cotton Disease Classification using DL/Images/MobileNet Accuracy.png
  Cotton Disease Classification using DL/Images/MobileNet Loss.png
  Cotton Disease Classification using DL/Images/Powdery Mildew.png
  Cotton Disease Classification using DL/Images/RESNET50 Accuracy.png
  Cotton Disease Classification using DL/Images/RESNET50 Loss.png
  Cotton Disease Classification using DL/Images/Target Spot.png
  Cotton Disease Classification using DL/Images/VGG16 Accuracy.png
  Cotton Disease Classification using DL/Images/VGG16 Loss.png
  Cotton Disease Classification using DL/Images/Xception Accuracy.png
  Cotton Disease Classification using DL/Images/Xception Loss.png
  Cotton Disease Classification using DL/Model/cotton-disease.ipynb
  Cotton Disease Classification using DL/README.md
  Cotton Disease Classification using DL/requirements.txt
Labels: Status: Approved, level3, gssoc

#779 [Project Addition] Plant Pathogen Detection using DL
  Plant Pathogen Detection using DL/Dataset/README.md
  Plant Pathogen Detection using DL/Images/Bacteria.png
  Plant Pathogen Detection using DL/Images/CNN Accuracy.png
  Plant Pathogen Detection using DL/Images/CNN Loss.png
  Plant Pathogen Detection using DL/Images/DENSENET121 Accuracy.png
  Plant Pathogen Detection using DL/Images/DENSENET121 Loss.png
  Plant Pathogen Detection using DL/Images/EDA.png
  Plant Pathogen Detection using DL/Images/Fungi.png
  Plant Pathogen Detection using DL/Images/Healthy.png
  Plant Pathogen Detection using DL/Images/InceptionV3 Accuracy.png
  Plant Pathogen Detection using DL/Images/InceptionV3 Loss.png
  Plant Pathogen Detection using DL/Images/MobileNet Accuracy.png
  Plant Pathogen Detection using DL/Images/MobileNet Loss.png
  Plant Pathogen Detection using DL/Images/NASNetMobile Accuracy.png
  Plant Pathogen Detection using DL/Images/NASNetMobile Loss.png
  Plant Pathogen Detection using DL/Images/Pests.png
  Plant Pathogen Detection using DL/Images/VGG16 Accuracy.png
  Plant Pathogen Detection using DL/Images/VGG16 Loss.png
  Plant Pathogen Detection using DL/Images/Virus.png
  Plant Pathogen Detection using DL/Images/Xception Accuracy.png
  Plant Pathogen Detection using DL/Images/Xception Loss.png
  Plant Pathogen Detection using DL/Model/plant-pathogen.ipynb
  Plant Pathogen Detection using DL/README.md
  Plant Pathogen Detection using DL/requirements.txt
Labels: Status: Approved, level3, gssoc

#790 Drowsiness detection using EEG signals using DL
  Drowsiness Detection using EEG signals/Dataset/readme.md
  Drowsiness Detection using EEG signals/Images/Result.png
  Drowsiness Detection using EEG signals/Images/model_acc1.png
  Drowsiness Detection using EEG signals/Images/model_acc2.png
  Drowsiness Detection using EEG signals/Images/model_acc3.png
  Drowsiness Detection using EEG signals/Images/model_loss1.png
  Drowsiness Detection using EEG signals/Images/model_loss2.png
  Drowsiness Detection using EEG signals/Images/model_loss3.png
  Drowsiness Detection using EEG signals/README.md
  Drowsiness Detection using EEG signals/model/Drowsiness_detection_models.ipynb
  Drowsiness Detection using EEG signals/requirements.txt
Labels: Status: Approved, level2, gssoc

#791 Polyp Segmentation in Endoscopy Image
  Polyp Segmentation/Dataset/README.md
  Polyp Segmentation/Images/dataset_preview.png
  Polyp Segmentation/Images/deeplabv3+_architecture.png
  Polyp Segmentation/Images/deeplabv3+_graphs.png
  Polyp Segmentation/Images/deeplabv3+_results.png
  Polyp Segmentation/Images/resunet_architecture.png
  Polyp Segmentation/Images/resunet_graphs.png
  Polyp Segmentation/Images/resunet_results.png
  Polyp Segmentation/Images/unet_architecture.png
  Polyp Segmentation/Images/unet_graphs.png
  Polyp Segmentation/Images/unet_results.png
  Polyp Segmentation/Models/polyp-segmentation-deeplabv3.ipynb
  Polyp Segmentation/Models/polyp-segmentation-resunet.ipynb
  Polyp Segmentation/Models/polyp-segmentation-unet.ipynb
  Polyp Segmentation/README.md
Labels: Status: Approved, level2, gssoc

#806 Pet's Facial Expression Detection
  Pet's Facial Expression/Dataset/README.md
  Pet's Facial Expression/Images/ConfusionMatrix_ViT.png
  Pet's Facial Expression/Images/Dataset.png
  Pet's Facial Expression/Images/EfficientNet_plot.png
  Pet's Facial Expression/Images/ResNet50_Plot.png
  Pet's Facial Expression/Models/README.md
  Pet's Facial Expression/Models/pet-s-facial-expression-detection-resnet-50.ipynb
  Pet's Facial Expression/Models/pets-facial-expression-efficientnet.ipynb
  Pet's Facial Expression/Models/pets-facial-expression-vit.ipynb
  Pet's Facial Expression/README.md
Labels: Status: Approved, level2, gssoc

#814 Add Kidney Stone Detection
  Kidney Stone Detection/Dataset/README.md
  Kidney Stone Detection/Images/CNN1.png
  Kidney Stone Detection/Images/CNN2.png
  Kidney Stone Detection/Images/CNN3.png
  Kidney Stone Detection/Images/ResNet1.png
  Kidney Stone Detection/Images/Resnet2.png
  Kidney Stone Detection/Images/VGG1.png
  Kidney Stone Detection/Model/CNN,_VGG,_Resnet_for_Kidney_Disease_Classific.ipynb
  Kidney Stone Detection/Model/Kidney_Stone_detection2.ipynb
  Kidney Stone Detection/README.md
  Kidney Stone Detection/requirements.txt
Labels: Status: Approved, level2, gssoc

#822 Micromobility Lane Recognition
  Micromobility Lane Recognition/Dataset/Organized_dataset.csv
  Micromobility Lane Recognition/Dataset/README.md
  Micromobility Lane Recognition/Images/Bar-Chart-Label-Distribution.png
  Micromobility Lane Recognition/Images/CNN_ResNet_Accuracies.png
  Micromobility Lane Recognition/Images/Dublin01-GH010157-000004_anon.png
  Micromobility Lane Recognition/Images/Grouped-Bar-Chart-for-Time-of-Day.png
  Micromobility Lane Recognition/Images/Grouped-Bar-Chart-for-Weather-Conditions.png
  Micromobility Lane Recognition/Images/Paris-Paris_Dott02-000005_anon.png
  Micromobility Lane Recognition/Images/Pie-Chart-for-Surface-Type-Distribution.png
  Micromobility Lane Recognition/Images/Singapore-Singapore-000023_anon.png
  Micromobility Lane Recognition/Images/Stockholm-GH010128-000002_anon.png
  Micromobility Lane Recognition/Images/co-occurrence-heatmap.png
  Micromobility Lane Recognition/Model/.ipynb_checkpoints/models-checkpoint.ipynb
  Micromobility Lane Recognition/Model/README.md
  Micromobility Lane Recognition/Model/models.ipynb
  Micromobility Lane Recognition/requirements.txt
Labels: Status: Approved, Points Updated, level2, gssoc
