Repository abhisheks008/DL-Simplified, pull requests merged in 2024-02, with the labels that each got.

#480 README Enhancement - Avocados Classification
  Avocados Classification/README.md
Labels: documentation, Status: Approved, Level 2 (Basic), DWOC

#481 Added "Facial Emotion Detection" project
  Facial Emotion Detection/Dataset/README.md
  Facial Emotion Detection/Images/00_baseline_cnn/00_data_samples.png
  Facial Emotion Detection/Images/00_baseline_cnn/01_model_summary.png
  Facial Emotion Detection/Images/00_baseline_cnn/02_training_curves.png
  Facial Emotion Detection/Images/00_baseline_cnn/03_confusion_matrix.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/00_config1_training_curves.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/01_config1_confusion_matrix.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/02_config2_training_curves.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/03_config2_confusion_matrix.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/04_config3_training_curves.png
  Facial Emotion Detection/Images/01_data_augmentation_cnn/05_config3_confusion_matrix.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/00_noaug_featext_training_curves.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/01_noaug_featext_confusion_matrix.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/02_noaug_finetune_training_curves.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/03_noaug_finetune_confusion_matrix.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/04_aug_featext_training_curves.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/05_aug_featext_confusion_matrix.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/06_aug_finetune_training_curves.png
  Facial Emotion Detection/Images/02_transfer_learning_mobilenetv2/07_aug_finetune_confusion_matrix.png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/00_noaug_featext_training_curves.png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/01_noaug_featext_confusion_matrix.png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/02_noaug_finetune_training_curves.png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/03_noaug_finetune_confusion_matrix.png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/04_aug_featext_training_curves.png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/05_aug_featext_confusion_matrix.png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/06_aug_finetune_training_curves.png
  Facial Emotion Detection/Images/03_transfer_learning_efficientnetv2/07_aug_finetune_confusion_matrix.png
  Facial Emotion Detection/Model/00_baseline_cnn.ipynb
  Facial Emotion Detection/Model/01_data_augmentation_cnn.ipynb
  Facial Emotion Detection/Model/02_transfer_learning_mobilenetv2.ipynb
  Facial Emotion Detection/Model/03_transfer_learning_efficientnetv2.ipynb
  Facial Emotion Detection/Model/README.md
  Facial Emotion Detection/Model/requirements.txt
  Facial Emotion Detection/README.md
Labels: Status: Approved, Level: HARD, SWOC S4

#450 Brand Sentiment Analysis using NLP
  Brand Sentiment Analysis using NLP/Dataset/Dataset - Test.csv
  Brand Sentiment Analysis using NLP/Dataset/Dataset - Train.csv
  Brand Sentiment Analysis using NLP/Dataset/Dataset Card.csv
  Brand Sentiment Analysis using NLP/Images/Brand_names.jpg
  Brand Sentiment Analysis using NLP/Images/sentiment_analysis.jpg
  Brand Sentiment Analysis using NLP/models/README.md
  Brand Sentiment Analysis using NLP/models/analysis.ipynb
  Brand Sentiment Analysis using NLP/models/model1.ipynb
  Brand Sentiment Analysis using NLP/models/model2.ipynb
  Brand Sentiment Analysis using NLP/models/model3.ipynb
  Brand Sentiment Analysis using NLP/requirements.txt
Labels: Status: Approved, Level: MEDIUM, SWOC S4

#483 Durum Wheat Classification using DL
  Durum Wheat Classification using DL/README.md
  Durum Wheat Classification using DL/dataset/README.md
  Durum Wheat Classification using DL/images/DenseNet.png
  Durum Wheat Classification using DL/images/ResNet50.png
  Durum Wheat Classification using DL/images/eda.png
  Durum Wheat Classification using DL/images/efficientnet.png
  Durum Wheat Classification using DL/images/flipped.png
  Durum Wheat Classification using DL/images/inceptionNet.png
  Durum Wheat Classification using DL/images/original vs grayscale.png
  Durum Wheat Classification using DL/images/original vs resized.png
  Durum Wheat Classification using DL/images/rotated.png
  Durum Wheat Classification using DL/model/durum wheat.ipynb
  Durum Wheat Classification using DL/requirements.txt
Labels: Status: Approved, Level: MEDIUM, SWOC S4

#492 Shoe vs Sandal vs Boot Image Classification #466
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (1143).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (1264).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (1385).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (1506).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (2474).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (2595).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (2716).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (2837).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (2958).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (3926).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (4047).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (4168).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (4289).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (4410).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Boot/boot (975).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (1089).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (1210).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (1331).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (1452).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (2420).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (2541).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (2662).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (2783).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (2904).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (3872).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (3993).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (4114).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (4235).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (4356).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Sandal/Sandal (968).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (1089).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (1210).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (1331).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (1452).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (2420).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (2541).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (2662).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (2783).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (2904).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (3872).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (3993).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (4114).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (4235).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (4356).jpg
  Shoe vs Sandal vs Boot Image Classification/Dataset/Shoe/Shoe (968).jpg
  Shoe vs Sandal vs Boot Image Classification/Image/accuracy_plot_model3.png
  Shoe vs Sandal vs Boot Image Classification/Image/loss_plot_model3.png
  Shoe vs Sandal vs Boot Image Classification/Model/README.md
  Shoe vs Sandal vs Boot Image Classification/Model/model1.ipynb
  Shoe vs Sandal vs Boot Image Classification/Model/model2.ipynb
  Shoe vs Sandal vs Boot Image Classification/requirements.txt
Labels: Status: Approved, Level 3 (Intermediate), DWOC

#494 Spam Vs Ham Mail Classification [With Streamlit GUI]
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Dataset/newData.csv
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Dataset/spam-vs-ham-dataset.csv
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Image/PairPlot_withHue.png
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Image/Spam-vs-ham-piechart.jpg
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Image/spam-ham-num_chr.jpg
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Image/spam-ham-num_sent.jpg
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Image/spam-ham-num_word.jpg
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Model/README.md
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Model/app1.py
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Model/app2.py
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Model/model1.ipynb
  Spam Vs Ham Mail Classification [With Streamlit GUI]/Model/model2.ipynb
  Spam Vs Ham Mail Classification [With Streamlit GUI]/requirements.txt
Labels: Status: Approved, Level: HARD, SWOC S4

#495 Cardiovascular Disease Risk Prediction DL Model
  Cardiovascular Disease Risk Prediction Model/Dataset/README.md
  Cardiovascular Disease Risk Prediction Model/Images/Age_Category_distribution.png
  Cardiovascular Disease Risk Prediction Model/Images/Alcohol_Consumption_bivariant_distribution.png
  Cardiovascular Disease Risk Prediction Model/Images/Alcohol_Consumption_distribution.png
  Cardiovascular Disease Risk Prediction Model/Images/BMI_distribution.png
  Cardiovascular Disease Risk Prediction Model/Images/DNN_Model.png
  Cardiovascular Disease Risk Prediction Model/Images/Fruit_Consumption_bivariant_distribution.png
  Cardiovascular Disease Risk Prediction Model/Images/Height_(cm)_bivariant_distribution.png
  Cardiovascular Disease Risk Prediction Model/Images/LSTM_Model.png
  Cardiovascular Disease Risk Prediction Model/Images/RNN_Model.png
  Cardiovascular Disease Risk Prediction Model/Images/characteristic_curve.png
  Cardiovascular Disease Risk Prediction Model/Images/correlation_heatmap.png
  Cardiovascular Disease Risk Prediction Model/Images/target_correlation.png
  Cardiovascular Disease Risk Prediction Model/Model/Cardiovascular Disease Risk Prediction Model.ipynb
  Cardiovascular Disease Risk Prediction Model/README.md
  Cardiovascular Disease Risk Prediction Model/requirements.txt
Labels: Status: Approved, Level: HARD, SWOC S4

#498 Persian Alphabets Classification using NLP
  Persian Alphabets Classification/README.md
  Persian Alphabets Classification/dataset/readme.md
  Persian Alphabets Classification/images/accuracy.png
  Persian Alphabets Classification/images/cnn_accuracy.png
  Persian Alphabets Classification/images/cnn_loss.png
  Persian Alphabets Classification/images/hybrid_model_acc.png
  Persian Alphabets Classification/images/hybrid_model_loss.png
  Persian Alphabets Classification/images/loss.png
  Persian Alphabets Classification/images/lstm_acc.png
  Persian Alphabets Classification/images/lstm_loss.png
  Persian Alphabets Classification/models/cnn_model.h5
  Persian Alphabets Classification/models/hybrid_model.h5
  Persian Alphabets Classification/models/lstm_model.h5
  Persian Alphabets Classification/models/notebook.ipynb
  Persian Alphabets Classification/models/readme.md
  Persian Alphabets Classification/requirements.txt
Labels: Status: Approved, Level: HARD, SWOC S4

#497 Celebrity Faces Detection Model
  Celebrity Faces Detection Model/Dataset/README.md
  Celebrity Faces Detection Model/Images/Attractive_distribution.png
  Celebrity Faces Detection Model/Images/accuracy_inception.png
  Celebrity Faces Detection Model/Images/accuracy_resnet101v2.png
  Celebrity Faces Detection Model/Images/accuracy_resnet50.png
  Celebrity Faces Detection Model/Images/data_augmentation.png
  Celebrity Faces Detection Model/Images/lefteye_x_and_lefteye_y.png
  Celebrity Faces Detection Model/Images/leftmouth_x_and_leftmouth_y.png
  Celebrity Faces Detection Model/Images/loss_function_inception.png
  Celebrity Faces Detection Model/Images/loss_function_resnet101v2.png
  Celebrity Faces Detection Model/Images/loss_function_resnet50.png
  Celebrity Faces Detection Model/Images/nose_x_and_nose_y.png
  Celebrity Faces Detection Model/Images/righteye_x_and_righteye_y.png
  Celebrity Faces Detection Model/Images/rightmouth_x_and_rightmouth_y.png
  Celebrity Faces Detection Model/Images/width_and_height.png
  Celebrity Faces Detection Model/Images/x_1_and_y_1.png
  Celebrity Faces Detection Model/Model/celebrity_faces_detection_model.ipynb
  Celebrity Faces Detection Model/README.md
  Celebrity Faces Detection Model/requirements.txt
Labels: Status: Approved, Level: HARD, SWOC S4
