Repository abhisheks008/DL-Simplified, pull requests merged in 2024-01, with the labels that each got.

#423 Fusarium Wilt Disease Detection using DL
  Fusarium Wilt Disease Detection/README.md
  Fusarium Wilt Disease Detection/dataset/README.md
  Fusarium Wilt Disease Detection/images/DenseNet210.jpg
  Fusarium Wilt Disease Detection/images/EDA.png
  Fusarium Wilt Disease Detection/images/MobileNet.jpg
  Fusarium Wilt Disease Detection/images/VGG16.jpg
  Fusarium Wilt Disease Detection/images/bar plot.png
  Fusarium Wilt Disease Detection/images/dataset image visualization.png
  Fusarium Wilt Disease Detection/images/train vs val loss for vgg 16.png
  Fusarium Wilt Disease Detection/model/model.ipynb
  Fusarium Wilt Disease Detection/requirements.txt
Labels: Status: Approved, Level: MEDIUM, SWOC S4

#425 Car Price Prediction using DL #339
  Car Price Prediction using DL/Dataset/CarPrice_Assignment.csv
  Car Price Prediction using DL/Images/CorrelationHeatmap.png
  Car Price Prediction using DL/Images/ErrorValuesBarPlot.png
  Car Price Prediction using DL/Images/PairPlot.png
  Car Price Prediction using DL/Images/Scatter_Predicted_vs_Actual.png
  Car Price Prediction using DL/Images/TrainingHistoryPlot.png
  Car Price Prediction using DL/Images/box_CarBody_vs_Price.png
  Car Price Prediction using DL/Images/interactive_3d_scatter_plot.html
  Car Price Prediction using DL/Images/interactive_3d_scatter_plot.svg
  Car Price Prediction using DL/Model/Car_Price_Prediction_with_DL.ipynb
  Car Price Prediction using DL/Model/Complex Neural Network_model.h5
  Car Price Prediction using DL/Model/LSTM_model.h5
  Car Price Prediction using DL/Model/MLP_model.h5
  Car Price Prediction using DL/Model/README.md
  Car Price Prediction using DL/Model/Simple Neural Network_model.h5
  Car Price Prediction using DL/Model/Simple RNN_model.h5
  Car Price Prediction using DL/Model/model_complex_best_model.keras
  Car Price Prediction using DL/requirements.txt
Labels: Status: Approved, Level: HARD, SWOC S4

#427 Track fault detection using DL
  Railway Track Fault Detection/Model/conv.py
  Track Fault Detection using DL/README.md
  Track Fault Detection using DL/dataset/README.md
  Track Fault Detection using DL/images/InceptionV3_model.png
  Track Fault Detection using DL/images/ResNet.png
  Track Fault Detection using DL/images/cf_matrix_vgg16.png
  Track Fault Detection using DL/images/densenet.png
  Track Fault Detection using DL/images/inceptionV3.png
  Track Fault Detection using DL/images/mobileNet.png
  Track Fault Detection using DL/images/vgg16.png
  Track Fault Detection using DL/model/model.ipynb
  Track Fault Detection using DL/requirements.txt
Labels: Status: Approved, Level: MEDIUM, SWOC S4

#432 Popular Quotes Author Classifier Using NLP
  Popular Quotes Author Classifier using NLP/Dataset/Autor_detection.csv
  Popular Quotes Author Classifier using NLP/Images/EDA.png
  Popular Quotes Author Classifier using NLP/Images/Pie.png
  Popular Quotes Author Classifier using NLP/Images/Sample_Distrib.png
  Popular Quotes Author Classifier using NLP/Model/README.md
  Popular Quotes Author Classifier using NLP/Model/final_model.ipynb
  Popular Quotes Author Classifier using NLP/requirements.txt
Labels: Status: Approved, Level: MEDIUM, SWOC S4

#433 Created Pothole Detection System
  Pothole Detection System/Dataset/README.md
  Pothole Detection System/Images/AUCs.png
  Pothole Detection System/Images/README.md
  Pothole Detection System/Images/ann_history.png
  Pothole Detection System/Images/cnn_history.png
  Pothole Detection System/Images/dataset1.png
  Pothole Detection System/Images/dataset2.png
  Pothole Detection System/Images/dataset3.png
  Pothole Detection System/Images/inception_history.png
  Pothole Detection System/Images/preprocessed1.png
  Pothole Detection System/Images/preprocessed2.png
  Pothole Detection System/Model/README.md
  Pothole Detection System/Model/potholes-detection-system.ipynb
  Pothole Detection System/Model/requirements.txt
Labels: Status: Approved, Level: MEDIUM, SWOC S4

#436 Bone Marrow Cells Classification using Deep Learning
  Bone Marrow Cells Classification using Deep Learning/README.md
  Bone Marrow Cells Classification using Deep Learning/dataset/README.md
  Bone Marrow Cells Classification using Deep Learning/images/DenseNet.png
  Bone Marrow Cells Classification using Deep Learning/images/EDA.png
  Bone Marrow Cells Classification using Deep Learning/images/VGG16.png
  Bone Marrow Cells Classification using Deep Learning/images/efficient net b5.png
  Bone Marrow Cells Classification using Deep Learning/images/mobileNet.png
  Bone Marrow Cells Classification using Deep Learning/model/model.ipynb
  Bone Marrow Cells Classification using Deep Learning/requirements.txt
Labels: Status: Approved, Level: MEDIUM, SWOC S4

#431 ChatGPT Sentiment Analysis
  ChatGPT Based Tweets Sentiment Analysis Using DL/Dataset/Dataset link
  ChatGPT Based Tweets Sentiment Analysis Using DL/Dataset/README
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/Analysis.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/BarChart.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/CnnModelAccuracyGraph.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/CnnModelLossGraph.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/LogisticRegressionGraph.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/LstmAccuracyGraph.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/LstmLossGraph.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/NaiveBayesGraph.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/PerHour.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/PerMinute.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/RandomForestGraph.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/Trial&AccuracyGraph1.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/Trial&AccuracyGraph2.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/WordCloudAfterCleaning.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Images/WordCloudBeforeCleaning.png
  ChatGPT Based Tweets Sentiment Analysis Using DL/Model/ChatGPT_SA using DL.ipynb
  ChatGPT Based Tweets Sentiment Analysis Using DL/Model/ChatGPT_SA_using_DL_updated.ipynb
  ChatGPT Based Tweets Sentiment Analysis Using DL/Model/UPDATED tweet chatgpt sentiment analysis.ipynb
  ChatGPT Based Tweets Sentiment Analysis Using DL/Readme.md
Labels: Status: Approved, Level: MEDIUM, Points Updated, SWOC S4

#451 Added Cassava Leaf Disease Classification. #418
  Cassava Leaf Disease Classification/Dataset/README.md
  Cassava Leaf Disease Classification/Images/densenet_cm.png
  Cassava Leaf Disease Classification/Images/densenet_plots.png
  Cassava Leaf Disease Classification/Images/efficientnet_cm.png
  Cassava Leaf Disease Classification/Images/efficientnet_plots.png
  Cassava Leaf Disease Classification/Images/inceptionv3_cm.png
  Cassava Leaf Disease Classification/Images/inceptionv3_plots.png
  Cassava Leaf Disease Classification/Images/mobilenet_cm.png
  Cassava Leaf Disease Classification/Images/mobilenetv2_plots.png
  Cassava Leaf Disease Classification/Images/model_comparison.png
  Cassava Leaf Disease Classification/Images/sample_images.png
  Cassava Leaf Disease Classification/Model/Cassava_leaf_disease_classification.ipynb
  Cassava Leaf Disease Classification/README.md
  Cassava Leaf Disease Classification/requirements.txt
Labels: Status: Approved, Level: HARD, SWOC S4

#455 Cassava Leaf Disease Classification using DL
  Cassava Leaf Disease Classification using DL/README.md
  Cassava Leaf Disease Classification using DL/dataset/README.md
  Cassava Leaf Disease Classification using DL/images/ResNet50_1.png
  Cassava Leaf Disease Classification using DL/images/bar plot.png
  Cassava Leaf Disease Classification using DL/images/denseNet.png
  Cassava Leaf Disease Classification using DL/images/diseases.png
  Cassava Leaf Disease Classification using DL/images/efficientNet_1.png
  Cassava Leaf Disease Classification using DL/images/gray.png
  Cassava Leaf Disease Classification using DL/images/inceptionNet_1.png
  Cassava Leaf Disease Classification using DL/images/mobileNetV2_1.png
  Cassava Leaf Disease Classification using DL/images/original vs res.png
  Cassava Leaf Disease Classification using DL/images/pie chart.png
  Cassava Leaf Disease Classification using DL/model/model.ipynb
  Cassava Leaf Disease Classification using DL/requirements.txt
Labels: Status: Approved, Level: HARD, SWOC S4

#476 README Enhancement - Brain Tumor Detection
  Brain Tumor Detection/Dataset/README.md
  Brain Tumor Detection/Dataset/converpic.jpg
  Brain Tumor Detection/Images/cnn_plot.png
  Brain Tumor Detection/Images/resnet50.png
  Brain Tumor Detection/Images/vgg_plot.png
  Brain Tumor Detection/Model/Brain_Tumor_Detection_1.ipynb
  Brain Tumor Detection/Model/README.md
Labels: Status: Approved, Level: EASY, SWOC S4

#477 Cricket Shots Detection
  Cricket Shots Detection/README.md
  Cricket Shots Detection/dataset/README.md
  Cricket Shots Detection/images/bar.png
  Cricket Shots Detection/images/dense.png
  Cricket Shots Detection/images/eda_cric.png
  Cricket Shots Detection/images/efficient.png
  Cricket Shots Detection/images/inception.png
  Cricket Shots Detection/images/pie chart.png
  Cricket Shots Detection/images/resnet.png
  Cricket Shots Detection/model/cricket shots.ipynb
  Cricket Shots Detection/requirements.txt
Labels: Status: Approved, Level: HARD, SWOC S4

#479 Payment Fraud Detection using Deep Learning
  Payment Fraud Detection using DL/Dataset/README.md
  Payment Fraud Detection using DL/Images/Correlation Matrix.png
  Payment Fraud Detection using DL/Images/Count of all type of transaction.png
  Payment Fraud Detection using DL/Images/Count of frauds.png
  Payment Fraud Detection using DL/Images/Number of transaction by Type of transaction and isFlaggedFraud.png
  Payment Fraud Detection using DL/Images/Number of transaction by Type of transaction and isFraud.png
  Payment Fraud Detection using DL/Images/README.md
  Payment Fraud Detection using DL/Model/Payments Fraud Detection using DL.ipynb
  Payment Fraud Detection using DL/Model/README.md
  Payment Fraud Detection using DL/Model/RNN_LSTM.model
  Payment Fraud Detection using DL/Model/multiple_input_neural_network.model
  Payment Fraud Detection using DL/Model/single_input_neural_network.model
  Payment Fraud Detection using DL/reqiurement.txt
Labels: Status: Approved, Level: MEDIUM, SWOC S4
