Repository abhisheks008/DL-Simplified, pull requests merged in 2024-10, with the labels that each got.

#896 Stock Analysis
  Stock Analysis/Dataset/README.md
  Stock Analysis/Dataset/tesla-stock-price.csv
  Stock Analysis/Images/cnn_stock_prediction.png
  Stock Analysis/Images/gru_stock_prediction.png
  Stock Analysis/Images/lstm_stock_prediction.png
  Stock Analysis/Images/rnn_stock_prediction.png
  Stock Analysis/Model/README.md
  Stock Analysis/Model/model_cnn.ipynb
  Stock Analysis/Model/model_gru.ipynb
  Stock Analysis/Model/model_lstm.ipynb
  Stock Analysis/Model/model_rnn.ipynb
  Stock Analysis/requirements.txt
Labels: Status: Approved, level 2, hacktoberfest-accepted, gssoc-ext

#899 feat:Bird species classification
  Bird Species Classification/Dataset/Readme.md
  Bird Species Classification/Images/InceptionV3.png
  Bird Species Classification/Images/inception_resnet_v2.png
  Bird Species Classification/Images/masked_image_1.png
  Bird Species Classification/Images/masked_image_2.png
  Bird Species Classification/Images/masked_image_3.png
  Bird Species Classification/Model/bird_species_classification.ipynb
  Bird Species Classification/Readme.md
  Bird Species Classification/requirements.txt
Labels: Status: Approved, level 2, hacktoberfest-accepted, gssoc-ext

#949 Documentation: Enhancement Of Contributing.md
  CONTRIBUTING.md
Labels: Status: Approved, level 1, hacktoberfest-accepted, hacktoberfest, gssoc-ext

#943 Deepfake Images Detector using DL
  Deepfake Images Detector/Dataset/README.md
  Deepfake Images Detector/Images/Pixel_Distribution.png
  Deepfake Images Detector/Images/Sample_Images.png
  Deepfake Images Detector/Images/Test_Class_Distribution_Plot.png
  Deepfake Images Detector/Images/Train_Class_Distribution_Plot.png
  Deepfake Images Detector/Images/Validation_Class_Distribution_Plot.png
  Deepfake Images Detector/Model/Deepfake_Image_Detector.ipynb
  Deepfake Images Detector/README.md
  Deepfake Images Detector/requirements.txt
Labels: Status: Approved, level 2, hacktoberfest-accepted, hacktoberfest, gssoc-ext

#930 Traffic Accident Prediction Model using Deep Learning
  Traffic Accident Prediction Model using Deep Learning /Dataset/README.md
  Traffic Accident Prediction Model using Deep Learning /Images/image
  Traffic Accident Prediction Model using Deep Learning /Images/image 1.png
  Traffic Accident Prediction Model using Deep Learning /Images/image 2. png
  Traffic Accident Prediction Model using Deep Learning /Images/image 3 .png
  Traffic Accident Prediction Model using Deep Learning /Model/README.md
  Traffic Accident Prediction Model using Deep Learning /Model/Traffic Accident Prediction Model using Deep Learning.ipynb
  Traffic Accident Prediction Model using Deep Learning /requirements.txt
Labels: Status: Approved, level 2, hacktoberfest-accepted, hacktoberfest, gssoc-ext

#950 Drone Navigation Detection and Path Tracing
  Drone Navigation Detection using Reinforcement Learning techniques/Dataset/Dataset- Explanations
  Drone Navigation Detection using Reinforcement Learning techniques/Dataset/datset_info
  Drone Navigation Detection using Reinforcement Learning techniques/Images/3D Path Finding Cost Suraface schematic.png
  Drone Navigation Detection using Reinforcement Learning techniques/Images/Drone Nav Graph.png
  Drone Navigation Detection using Reinforcement Learning techniques/Images/Drone Navigation Graph.png
  Drone Navigation Detection using Reinforcement Learning techniques/Images/Navigation Graph.png
  Drone Navigation Detection using Reinforcement Learning techniques/Images/a star graph.png
  Drone Navigation Detection using Reinforcement Learning techniques/Images/env graph.png
  Drone Navigation Detection using Reinforcement Learning techniques/Images/img files
  Drone Navigation Detection using Reinforcement Learning techniques/Images/pathfinding_heat-map.png
  Drone Navigation Detection using Reinforcement Learning techniques/Model/Drone_Navigation_Detection (1).ipynb
  Drone Navigation Detection using Reinforcement Learning techniques/Model/README.md
  Drone Navigation Detection using Reinforcement Learning techniques/requirements.txt
Labels: Status: Approved, level 2, hacktoberfest-accepted, hacktoberfest, gssoc-ext

#953 ADD INTRODUCTION AND OVERVIEW ALONG WITH TABLE OF CONTENT
  README.md
Labels: Status: Approved, level 1, hacktoberfest-accepted, hacktoberfest, gssoc-ext

#961 Online Food Delivery Preferences
  Online Food Delivery Preferences/Dataset/Onlinedeliverydata.csv
  Online Food Delivery Preferences/Dataset/README.md
  Online Food Delivery Preferences/Images/AgeGroup.png
  Online Food Delivery Preferences/Images/CorrelationCalculation.png
  Online Food Delivery Preferences/Images/DemographicDetails.png
  Online Food Delivery Preferences/Images/FeaturesOnlineDelivery 1.png
  Online Food Delivery Preferences/Images/FeaturesOnlineDelivery 2.png
  Online Food Delivery Preferences/Images/FeaturesOnlineDelivery 3.png
  Online Food Delivery Preferences/Model/Model1.ipynb
  Online Food Delivery Preferences/Model/Model2.ipynb
  Online Food Delivery Preferences/Model/README.md
  Online Food Delivery Preferences/requirements.txt
Labels: Status: Approved, level 3, hacktoberfest-accepted, hacktoberfest, gssoc-ext
