Repository abhisheks008/DL-Simplified, pull requests merged in 2024-05, with the labels that each got.

#515 README Enhancement - Cats vs Dogs Classification using DL
  Cats vs Dogs Classification using DL/README.md
Labels: documentation, enhancement, Status: Approved, level1, gssoc

#530 README Enhancement of DL-Simplified Project Repository
  README.md
Labels: documentation, enhancement, good first issue, Status: Approved, level1, gssoc

#533 [README Enhancement]: Colour Detection using DL
  Colour Detection using DL/README.md
Labels: documentation, enhancement, good first issue, Status: Approved, level1, gssoc

#534 [README Enhancement]: ChatGPT-Based Tweets Sentiment Analysis Using Deep Learning
  ChatGPT Based Tweets Sentiment Analysis Using DL/README.md
  ChatGPT Based Tweets Sentiment Analysis Using DL/Readme.md
  ChatGPT Based Tweets Sentiment Analysis Using DL/requirement.txt
  ChatGPT Based Tweets Sentiment Analysis Using DL/requirements.txt
Labels: documentation, enhancement, good first issue, Status: Approved, level1, gssoc

#535 [README Enhancement]: Children vs Adults Classification
  Children vs Adults Classification using DL/Dataset/README.md
  Children vs Adults Classification using DL/Model/README.md
Labels: documentation, enhancement, good first issue, Status: Approved, level1, gssoc

#541 [README Enhancement]: AI Generated Fruits and Real Fruits Classification using Image Processing
  AI Generated Fruits and Real Fruits Classification using Image Processing/Model/README.md
  AI Generated Fruits and Real Fruits Classification using Image Processing/Model/readme.md
Labels: documentation, enhancement, good first issue, Status: Approved, level1, gssoc

#545 [README Enhancement]: Concrete Compressive Strength Prediction Using Deep Learning
  Concrete Compressive Strength/Models/Readme.Md
Labels: documentation, enhancement, good first issue, Status: Approved, level1, gssoc

#549 Face Verification Model
  Face Verification/Dataset/README.md
  Face Verification/Images/Face_verfication.png
  Face Verification/Images/Model.png
  Face Verification/Images/Siamese_model.png
  Face Verification/Images/Triplet_data.png
  Face Verification/Models/Siamese_Neural_Network.ipynb
  Face Verification/README.md
  Face Verification/requirements.txt
Labels: Status: Approved, level3, gssoc

#555 [README Enhancement]: Age and Sex Prediction
  AI Generated Fruits and Real Fruits Classification using Image Processing/Model/README.md
  Age and Sex Prediction/Model/README.md
Labels: documentation, enhancement, Status: Approved, level1, gssoc

#566 README Enhancement - Canola Diseases Detection #487
  Canola Diseases Prediction/Model/README.md
Labels: documentation, enhancement, Status: Approved, level1, gssoc

#565 [README Enhancement]: Chocolate Classification using DL #526
  Chocolate Classification using DL/README.md
Labels: documentation, enhancement, Status: Approved, level1, gssoc

#578 Fire And Smoke Prediction
  Fire And Smoke Detection/Dataset/readme.md
  Fire And Smoke Detection/Images/1.png
  Fire And Smoke Detection/Images/2.png
  Fire And Smoke Detection/Images/Screenshot 2024-05-15 200402.png
  Fire And Smoke Detection/Images/Screenshot 2024-05-16 124430.png
  Fire And Smoke Detection/Images/download.png
  Fire And Smoke Detection/Model/Fire_Detection.ipynb
  Fire And Smoke Detection/README.md
  Fire And Smoke Detection/requirements.txt
Labels: Status: Approved, Points Updated, level2, gssoc

#571 Diabetes Prediction using DL
  Diabetes Predictor/Dataset/README.md
  Diabetes Predictor/Dataset/diabetes.csv
  Diabetes Predictor/Images/Distribution plots.png
  Diabetes Predictor/Images/Model Metrics.png
  Diabetes Predictor/Images/Models  acc comaprision.png
  Diabetes Predictor/Images/README.md
  Diabetes Predictor/Images/age pie chart.png
  Diabetes Predictor/Images/app.png
  Diabetes Predictor/Images/boxplot.png
  Diabetes Predictor/Images/correlation matrix.png
  Diabetes Predictor/Images/diabetic.png
  Diabetes Predictor/Images/distribution of outcome.png
  Diabetes Predictor/Images/insulin & glucose.png
  Diabetes Predictor/Images/pairplot.png
  Diabetes Predictor/Models/Diabetes Prediction.ipynb
  Diabetes Predictor/Models/README.md
  Diabetes Predictor/Models/ann_model.h5
  Diabetes Predictor/Models/lstm_model.h5
  Diabetes Predictor/Models/rnn_model.h5
  Diabetes Predictor/README.md
  Diabetes Predictor/Web App/Demo.mp4
  Diabetes Predictor/Web App/README.md
  Diabetes Predictor/Web App/app.py
  Diabetes Predictor/Web App/snapshot.png
  Diabetes Predictor/requirements.txt
Labels: Status: Approved, Points Updated, level3, gssoc

#568 Heart Disease Prediction using Deep Learning
  Heart Disease Detection/Dataset/heart_failure_clinical_records_dataset 2.csv
  Heart Disease Detection/Images/Result.png
  Heart Disease Detection/Images/metrics.png
  Heart Disease Detection/Images/model1_acc.png
  Heart Disease Detection/Images/model1_loss.png
  Heart Disease Detection/Images/model2_acc.png
  Heart Disease Detection/Images/model2_loss.png
  Heart Disease Detection/Images/model3_acc.png
  Heart Disease Detection/Images/model3_loss.png
  Heart Disease Detection/Images/summary_model.png
  Heart Disease Detection/Model/Heart_disease_prediction .ipynb
  Heart Disease Detection/README.md
  Heart Disease Detection/requirements.txt
Labels: Status: Approved, Points Updated, level3, gssoc

#572 Chocolate Classification using DL
  Chocolate Classification using DL/Images/acc_CNN-Attention.png
  Chocolate Classification using DL/Model/Chocolate Classification using DL.ipynb
  Chocolate Classification using DL/Model/model.keras
  Chocolate Classification using DL/README.md
  Colour Detection using DL/README.md
Labels: Status: Approved, level3, gssoc

#579 Srinivas Tulu Handwriting detection
  Srinivas Tulu Handwriting Detection/Dataset/README.md
  Srinivas Tulu Handwriting Detection/Images/DenseNet.png
  Srinivas Tulu Handwriting Detection/Images/EDA.png
  Srinivas Tulu Handwriting Detection/Images/effnet.png
  Srinivas Tulu Handwriting Detection/Images/inceptionNet.png
  Srinivas Tulu Handwriting Detection/Model/handwriting.ipynb
  Srinivas Tulu Handwriting Detection/README.md
  Srinivas Tulu Handwriting Detection/requirements.txt
Labels: Status: Approved, level2, gssoc

#584 [Model Enhancement]: Leukaemia Classification using DL
  Chocolate Classification using DL/README.md
  Leukaemia Classification using DL/Images/CNN-Attention.png
  Leukaemia Classification using DL/Model/Leukaemia Classification using DL.ipynb
  Leukaemia Classification using DL/README.md
Labels: Status: Approved, level2, gssoc

#594 Web App for Artwork Image Recognition
  Artwork Image Recognition/WebApp/Readme.md
  Artwork Image Recognition/WebApp/app.py
  Artwork Image Recognition/WebApp/static/main.css
  Artwork Image Recognition/WebApp/templates/index.html
  Artwork Image Recognition/WebApp/templates/layout.html
  Artwork Image Recognition/requirements.txt
Labels: Status: Approved, Points Updated, level2, gssoc

#591 Crop Pest and Disease Detection using DL
  Crop Pest and Disease Detection using DL/Dataset/README.md
  Crop Pest and Disease Detection using DL/Images/ANN_Training.png
  Crop Pest and Disease Detection using DL/Images/CNN_Training.png
  Crop Pest and Disease Detection using DL/Images/ResNet(Basic)_Training.png
  Crop Pest and Disease Detection using DL/Images/VGG16_Training.png
  Crop Pest and Disease Detection using DL/Model/Crop_Pest_and_Disease_Detection_using_DL.ipynb
  Crop Pest and Disease Detection using DL/Model/Crop_Pest_and_Disease_Detection_using_DL_.py
  Crop Pest and Disease Detection using DL/Model/README.md
  Crop Pest and Disease Detection using DL/requirements.txt
Labels: Status: Approved, level3, gssoc

#585 Ethnicity Classification of Asian People
  Ethnicity Classification of Asian People/Dataset/README.md
  Ethnicity Classification of Asian People/Dataset/asian_people.csv
  Ethnicity Classification of Asian People/Images/README.md
  Ethnicity Classification of Asian People/Images/knn_cm.png
  Ethnicity Classification of Asian People/Images/mobilenetv2_cm.png
  Ethnicity Classification of Asian People/Images/mobilenetv2_curves.png
  Ethnicity Classification of Asian People/Images/resnet50_cm.png
  Ethnicity Classification of Asian People/Images/rf_cm.png
  Ethnicity Classification of Asian People/Images/sgd_cm.png
  Ethnicity Classification of Asian People/Images/vgg16_cm.png
  Ethnicity Classification of Asian People/Images/xception_cm.png
  Ethnicity Classification of Asian People/Model/EDA_Images/Aligned_cropped.png
  Ethnicity Classification of Asian People/Model/EDA_Images/Original.png
  Ethnicity Classification of Asian People/Model/EDA_Images/Stats.png
  Ethnicity Classification of Asian People/Model/README.md
  Ethnicity Classification of Asian People/Model/asian_ethnicity_classification.ipynb
  Ethnicity Classification of Asian People/requirements.txt
Labels: Status: Requested Changes, gssoc

#562 Rick and Morty Character Image Detection
  Rick and Morty Character Image Detection/Dataset/README.md
  Rick and Morty Character Image Detection/Images/InceptionV3_prediction.png
  Rick and Morty Character Image Detection/Images/MobileNetV2_prediction.png
  Rick and Morty Character Image Detection/Images/VGG16_prediction.png
  Rick and Morty Character Image Detection/Images/bar.png
  Rick and Morty Character Image Detection/Images/cross_tabulation.png
  Rick and Morty Character Image Detection/Images/path_distribution.png
  Rick and Morty Character Image Detection/Images/pie.png
  Rick and Morty Character Image Detection/Models/README.md
  Rick and Morty Character Image Detection/Models/models.ipynb
  Rick and Morty Character Image Detection/requirement.txt
Labels: Status: Approved, Points Updated, level2, gssoc

#619 Added the feature to auto comment on a new issue creation
  .github/workflows/auto-comment-on-issue.yml
Labels: Status: Approved, level1, gssoc

#621 Image De-Photobombing
  Image De-Photobombing/Dataset/readme.md
  Image De-Photobombing/Images/117_output.jpg
  Image De-Photobombing/Images/130.jpg
  Image De-Photobombing/Images/130_output (1).jpg
  Image De-Photobombing/Images/OpenCV_based.png
  Image De-Photobombing/Images/Screenshot 2024-05-23 003611.png
  Image De-Photobombing/Images/de_photobombed_image_DeepFillv2.jpg
  Image De-Photobombing/Images/opencv-based.png
  Image De-Photobombing/Images/unet-2.png
  Image De-Photobombing/Images/unet.png
  Image De-Photobombing/Model/image-de-photobombing-1-2.ipynb
  Image De-Photobombing/Model/image-de-photobombing-3.ipynb
  Image De-Photobombing/readme.md
  Image De-Photobombing/requirements.txt
Labels: Status: Approved, Points Updated, level2, gssoc

#625 [Model Enhancement and Feature Addition]: Bank Loan Approval Prediction with Web App #583
  Bank Loan Approval Prediction/Images/Age Distribution.png
  Bank Loan Approval Prediction/Images/Box Plot of income.png
  Bank Loan Approval Prediction/Images/CCAvg Distribution by Personal Loan.png
  Bank Loan Approval Prediction/Images/Distribution of Education.png
  Bank Loan Approval Prediction/Images/FNN_Accuracy.png
  Bank Loan Approval Prediction/Images/FNN_Loss.png
  Bank Loan Approval Prediction/Images/Mortgage Distribution by Personal Loan.png
  Bank Loan Approval Prediction/Images/TabNet_Accuracy.png
  Bank Loan Approval Prediction/Images/TabNet_Loss.png
  Bank Loan Approval Prediction/Images/Updated_Correlation_Matrix.png
  Bank Loan Approval Prediction/Images/WDNN_Accuracy.png
  Bank Loan Approval Prediction/Images/WDNN_Loss.png
  Bank Loan Approval Prediction/Model/FNN_TabNet_WDNN.ipynb
  Bank Loan Approval Prediction/Model/README.md
  Bank Loan Approval Prediction/Web App/README.md
  Bank Loan Approval Prediction/Web App/app.py
  Bank Loan Approval Prediction/Web App/demo.mp4
  Bank Loan Approval Prediction/Web App/saved_models/best_model.zip
  Bank Loan Approval Prediction/Web App/saved_models/label_encoders.pkl
  Bank Loan Approval Prediction/Web App/saved_models/zip_code_freq_encoder.pkl
  Bank Loan Approval Prediction/Web App/static/UniversalBank.csv
  Bank Loan Approval Prediction/Web App/templates/base.html
  Bank Loan Approval Prediction/Web App/templates/index.html
  Bank Loan Approval Prediction/Web App/templates/predict.html
  Bank Loan Approval Prediction/requirements.txt
Labels: Status: Approved, Points Updated, level3, gssoc, Feature: Model, Feature: Web App

#620 [Project Addition]: Waste Classification using DL
  Crop Pest and Disease Detection using DL/Model/Crop_Pest_and_Disease_Detection_using_DL.ipynb
  Waste Classification using DL/Dataset/README.md
  Waste Classification using DL/Images/ANN_Performance.png
  Waste Classification using DL/Images/CNN_Performance.png
  Waste Classification using DL/Images/MobileNetV2_Performance.png
  Waste Classification using DL/Images/ResNet50_Performance.png
  Waste Classification using DL/Images/VGG16_Performance.png
  Waste Classification using DL/Model/README.md
  Waste Classification using DL/Model/Waste_Classification_using_DL.ipynb
  Waste Classification using DL/requirements.txt
Labels: Status: Approved, Points Updated, level3, gssoc

#629 Myntra Fashion Product Analysis
  Myntra Fashion Product Analysis/Dataset/README.md
  Myntra Fashion Product Analysis/Images/1.png
  Myntra Fashion Product Analysis/Images/2.png
  Myntra Fashion Product Analysis/Images/3.png
  Myntra Fashion Product Analysis/Images/4.png
  Myntra Fashion Product Analysis/Model/MyntraDataset.ipynb
  Myntra Fashion Product Analysis/README.md
  Myntra Fashion Product Analysis/requirements.txt
Labels: Status: Approved, Points Updated, level2, gssoc

#628 Website Classification
  Website Classification/Dataset/README.md
  Website Classification/Images/Heatmap_mnb.jpeg
  Website Classification/Images/bilstm_accuracy_plot.png
  Website Classification/Images/bilstm_loss_plot.png
  Website Classification/Images/category_count_plot.png
  Website Classification/Images/category_pie_chart.png
  Website Classification/Images/confusion_matrix_mnb.png
  Website Classification/Images/model_accuracy_comparison.png
  Website Classification/Images/model_accuracy_plot_cnn.png
  Website Classification/Images/model_loss_plot_cnn.png
  Website Classification/Images/test_dataset_count_plot.png
  Website Classification/Images/train_dataset_count_plot.png
  Website Classification/Images/url_length_boxplot.png
  Website Classification/Images/url_length_distribution.png
  Website Classification/Model/README.md
  Website Classification/Model/Website_classification_mnb_cnn_lstm.ipynb
  Website Classification/requirements.txt
Labels: Status: Approved, Points Updated, level2, gssoc

#630 [Project Addition] Tiger Identification using DL
  Tiger Identification using DL/Dataset/README.md
  Tiger Identification using DL/Images/DenseNet_results.png
  Tiger Identification using DL/Images/EfficientNetB3_results.png
  Tiger Identification using DL/Images/ResNet50_results.png
  Tiger Identification using DL/Images/VGG16_results.png
  Tiger Identification using DL/Models/Tiger_re-indentification_VGG16.ipynb
  Tiger Identification using DL/Models/Tiger_re_indentification_DenseNet.ipynb
  Tiger Identification using DL/Models/Tiger_re_indentification_EfficientNetB3.ipynb
  Tiger Identification using DL/Models/Tiger_re_indentification_Resnet50.ipynb
  Tiger Identification using DL/Models/readme.md
  Tiger Identification using DL/README.md
Labels: Status: Approved, Points Updated, level2, gssoc

#632 added workflow for autocommenting on closing an issue
  .github/workflows/autocomment-iss-close.yml
Labels: Status: Approved, Points Updated, level1, gssoc

#559 README Enhancement - Cats vs Dogs Audio Classification using DL #488
  Cats vs Dogs Audio Classification using DL/README.md
Labels: Status: Approved, Points Updated, level1, gssoc

#635 [Project Addition]:Traffic Sign Recognition
  Traffic Sign Recognition/dataset/README.md
  Traffic Sign Recognition/images/ResNet50_prediction/don't_go_straight.png
  Traffic Sign Recognition/images/ResNet50_prediction/go_left_or_straight.png
  Traffic Sign Recognition/images/ResNet50_prediction/go_right-or_straight.png
  Traffic Sign Recognition/images/ResNet50_prediction/roundabout_mandatory.png
  Traffic Sign Recognition/images/ResNet50_prediction/speed_limit_60.png
  Traffic Sign Recognition/images/ResNet50_prediction/speed_limit_80.png
  Traffic Sign Recognition/images/VGG16_prediction/don't_go_straight.png
  Traffic Sign Recognition/images/VGG16_prediction/go_right.png
  Traffic Sign Recognition/images/VGG16_prediction/go_right2.png
  Traffic Sign Recognition/images/VGG16_prediction/go_right_and_straight.png
  Traffic Sign Recognition/images/VGG16_prediction/speed_limit_60.png
  Traffic Sign Recognition/images/VGG16_prediction/speed_limit_80.png
  Traffic Sign Recognition/images/Xception_prediction/Don't_go_straight.png
  Traffic Sign Recognition/images/Xception_prediction/Roundabout_mandatory.png
  Traffic Sign Recognition/images/Xception_prediction/go_right_or_straight.png
  Traffic Sign Recognition/images/Xception_prediction/roundabout_mandatory2.png
  Traffic Sign Recognition/images/Xception_prediction/speed_limit_60.png
  Traffic Sign Recognition/images/Xception_prediction/speed_limit_80Km.png
  Traffic Sign Recognition/images/bar.png
  Traffic Sign Recognition/images/cross_tabulation.png
  Traffic Sign Recognition/images/image_path_distribution.png
  Traffic Sign Recognition/images/pie.png
  Traffic Sign Recognition/models/README.md
  Traffic Sign Recognition/models/models_TrafficSignDetection_final.ipynb
  Traffic Sign Recognition/requirement.txt
Labels: Status: Approved, Points Updated, level2, gssoc

#641 Land use scene classification
  Land Use Scene Classification/Dataset/README.md
  Land Use Scene Classification/Images/Dataset Summary.png
  Land Use Scene Classification/Images/Result of MobilenetV3Large.png
  Land Use Scene Classification/Model/README.md
  Land Use Scene Classification/Model/land-use-scene-classification-mobilenetv3large.ipynb
  Land Use Scene Classification/Model/land-use-scene-classification-mobilenetv3small.ipynb
  Land Use Scene Classification/Model/land-use-scene-classification-resnet101v2.ipynb
  Land Use Scene Classification/Model/land-use-scene-classification-resnet50v2.ipynb
  Land Use Scene Classification/requirements.txt
Labels: Status: Approved, level3, gssoc

#642 ChatGPT Reddit Comments Analysis using NLP issue solved
  ChatGPT Reddit Comments Analysis using NLP/Dataset/README.md
  ChatGPT Reddit Comments Analysis using NLP/Images/category_added.png
  ChatGPT Reddit Comments Analysis using NLP/Images/dataset_part.png
  ChatGPT Reddit Comments Analysis using NLP/Images/piechart.png
  ChatGPT Reddit Comments Analysis using NLP/Images/plot_cnn+lstm.png
  ChatGPT Reddit Comments Analysis using NLP/Images/plot_cnn.png
  ChatGPT Reddit Comments Analysis using NLP/Images/plot_lstm.png
  ChatGPT Reddit Comments Analysis using NLP/Images/wordcloud1.png
  ChatGPT Reddit Comments Analysis using NLP/Images/wordcloud2.png
  ChatGPT Reddit Comments Analysis using NLP/Images/wordcloud3.png
  ChatGPT Reddit Comments Analysis using NLP/Model/ChatGPT_Reddit_comment_analysis_using_NLP (1).ipynb
  ChatGPT Reddit Comments Analysis using NLP/Model/READme.md
  ChatGPT Reddit Comments Analysis using NLP/requirements.txt
Labels: Status: Approved, level2, gssoc

#643 [Model and README Enhancement] Glass Bangle Defects Detection
  Glass Bangle Defects Detection using DL/Datasets/README.md
  Glass Bangle Defects Detection using DL/Images/CNN model.png
  Glass Bangle Defects Detection using DL/Images/CNN-Keras-Attention.png
  Glass Bangle Defects Detection using DL/Images/CNN-Keras.png
  Glass Bangle Defects Detection using DL/Images/CNN-architecture-based-on-GoogLeNet-model.ppm.png
  Glass Bangle Defects Detection using DL/Images/GoogleNet-Validation.png
  Glass Bangle Defects Detection using DL/Images/GoogleNet-train.png
  Glass Bangle Defects Detection using DL/Images/ResNet-Validation.png
  Glass Bangle Defects Detection using DL/Images/ResNet-training.png
  Glass Bangle Defects Detection using DL/Images/Residual-Block.PNG
  Glass Bangle Defects Detection using DL/Model/Custom-Model.ipynb
  Glass Bangle Defects Detection using DL/Model/Glass-Bangle-Defect-Detection.ipynb
  Glass Bangle Defects Detection using DL/README.md
  Glass Bangle Defects Detection using DL/requirements.txt
  Glass-Bangle-Defect-Detection/Model/Glass-Bangle-Defect-Detection.ipynb
Labels: Status: Approved, level2, gssoc

#649 Bone Fracture Detection
  Bone Fracture Detection/Dataset/README.md
  Bone Fracture Detection/Images/RCNN:results.png
  Bone Fracture Detection/Images/YOLO:confusion_matrix.png
  Bone Fracture Detection/Images/YOLO:results.png
  Bone Fracture Detection/Models/Bone_Fracture_RCNN.ipynb
  Bone Fracture Detection/Models/Bone_Fracture_YOLO.ipynb
  Bone Fracture Detection/README.md
Labels: Status: Approved, level2, gssoc

#658 Adverse Weather Classification
  Adverse Weather Classification/Dataset/README.md
  Adverse Weather Classification/Images/1.png
  Adverse Weather Classification/Images/2.png
  Adverse Weather Classification/Images/3.png
  Adverse Weather Classification/Model/Weather Classifcation.ipynb
  Adverse Weather Classification/README.md
  Adverse Weather Classification/requirements.txt
Labels: Status: Approved, level3, gssoc
